objc + swift pagination guide
Nexmo/nexmo-developer pull request #3096
Opened 2020-08-12 14:20 UTC by abdulajet

## Description

Adding pagination guide for swift and objc. 

swift: 
objc:

2020-08-24 10:09 UTC, pardel requested changes
Could we unify the names please?

2020-08-24 10:09 UTC, pardel commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-next-event-page/objective_c.md
> +if (events.hasNextPage) {
please rename events to eventsPage

2020-08-24 10:09 UTC, pardel commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-next-event-page/swift.md
> +if page.hasNextPage() {
please rename page to eventsPage

2020-08-24 10:09 UTC, pardel commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-prev-event-page/objective-c.md
> +if (events.hasPreviousPage) {
please rename events to eventsPage

2020-08-24 10:09 UTC, pardel commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-prev-event-page/swift.md
> +if page.hasPreviousPage() {
please rename page to eventsPage

2020-08-25 10:11 UTC, pardel requested changes

2020-08-25 10:11 UTC, pardel commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-page-events/objective_c.md
> +    self.eventsPage = [NSMutableArray arrayWithArray:events.events];
Sorry, I believe these are actual events and not eventsPage.

2020-08-25 10:11 UTC, pardel commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-page-events/swift.md
> +    self.eventsPage = page?.events
Same thing. `page?.events` returns an array of events rather than an eventsPage.

2020-08-25 10:13 UTC, abdulajet commented on _tutorials_tabbed_content/client-sdk/guides/messaging/handling-pagnation/load-page-events/objective_c.md
> +    self.eventsPage = [NSMutableArray arrayWithArray:events.events];
Yes sorry i was distracted, they are events. I already posted about event parameter, `NXMEventsPage`, renaming

2020-08-25 10:34 UTC, pardel approved these changes
Looks good

2020-08-25 10:38 UTC, merged