Devx 4182 updated user names
Nexmo/nexmo-developer pull request #3119
Opened 2020-08-20 20:07 UTC by igorwojda

## Description

Main change - update used names `User1` to `Bob` and `User2` to `Alice`

## Deploy Notes

https://nexmo-developer-pr-3118.herokuapp.com/client-sdk/tutorials/in-app-messaging/introduction/android

2020-08-24 11:17 UTC, tbedford commented
Merge conflicts need fixing.

2020-08-24 15:01 UTC, tbedford requested changes
Not quite sure why an Android-related affects so many iOS-related files. Was the last merge commit good? Also, date needs to be changed to 21st August 2020 - at the moment is says "21h".

2020-08-25 09:36 UTC, igorwojda commented
I have removed bunch of iOS related changes and fixed iOS colons.

2020-08-25 10:56 UTC, tbedford approved these changes

2020-08-25 10:57 UTC, merged