App to app call objc tutorial
Nexmo/nexmo-developer pull request #3133
Opened 2020-08-25 17:29 UTC by abdulajet

## Description

Ticket: https://nexmoinc.atlassian.net/browse/DEVX-3860

Had to update swift paths too, so swift version linked. Also made minor corrections in a few other files

Old swift version: https://developer.nexmo.com/client-sdk/tutorials/app-to-app/introduction/swift
Swift version:  https://nexmo-developer-pr-3125.herokuapp.com /client-sdk/tutorials/app-to-app/introduction/swift
Objc version:  https://nexmo-developer-pr-3125.herokuapp.com/client-sdk/tutorials/app-to-app/introduction/objective_c

2020-08-26 13:41 UTC, pardel requested changes
Overall looks really good - I've included couple of changes to be made.

Also, let's aim to only include changes related to the topic we're tackling - this PR includes changes to the in-app messaging Obj-C tutorials. No need to revert it this time.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/permissions/objective_c.md
> +![Info.plist](/images/client-sdk/ios-in-app-voice/info-plist.png)
Could we include a Obj-C specific screenshot? We're using the same one as Swift and some users might find it confusing.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/call-ui/objective_c.md
> +To be able to call, you will need to create a new View Controller for the calling interface. From the Xcode menu, select `File` > `New` > `File...`. Choose a *Cocoa Touch Class*, name it `CallViewCon
This should ask user to select Objective-C as the language.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/call-ui/objective_c.md
> +Open `CallViewController.m` and add it programmatically.
add *them* programmatically.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/create-model/objective_c.md
> +To do this you will create a new User `Class`. From the Xcode menu, select `File` > `New` > `File...`. Select `Cocoa Touch Class`, name it `User` with a subclass of `NSObject`:
We need to ask them to make sure `Objective-C` is selected as the `Language`.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/create-model/objective_c.md
> +![Xcode adding file](/images/client-sdk/ios-messaging/userclass.png)
Could we please use the default Xcode theme for screenshots?

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/receive-call/objective_c.md
> +    [NSNotificationCenter.defaultCenter postNotificationName:@"NXMClient.incommingCall" object:call];
Could we drop a `m` from the name of that notification? Should be `NXMClient.incomingCall`.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/receive-call/objective_c.md
> +    [NSNotificationCenter.defaultCenter addObserver:self selector:@selector(didReceiveCall:) name:@"NXMClient.incommingCall" object:nil];
Same drop for a `m` from the name of that notification. Should be `NXMClient.incomingCall`.

2020-08-26 13:41 UTC, pardel commented on _tutorials/en/client-sdk/in-app-messaging/conversation-ui/objective_c.md
> +This will create a new file called `ChatViewController.m`, at the top import `NexmoClient` and `User`.
We should really make the PRs atomic. This PR seems to include lots of changes to the in-app-messaging Obj-C tutorial as well.

2020-08-26 13:54 UTC, abdulajet commented on _tutorials/en/client-sdk/app-to-app/permissions/objective_c.md
> +![Info.plist](/images/client-sdk/ios-in-app-voice/info-plist.png)
How do you feel about cropping it like this to allow for easier reusability?

![Screenshot 2020-08-26 at 14 53 56](https://user-images.githubusercontent.com/15106299/91312314-02778580-e7ac-11ea-9477-d95b607158ac.png)

2020-08-26 14:21 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/permissions/objective_c.md
> +![Info.plist](/images/client-sdk/ios-in-app-voice/info-plist.png)
Yes. That should do the trick.

2020-08-27 11:14 UTC, pardel approved these changes

2020-08-27 11:16 UTC, pardel requested changes
The Obj-C version is missing the "Create a NCCO" step. 
eg.: https://nexmo-developer-pr-3133.herokuapp.com/client-sdk/tutorials/app-to-app/client-sdk/phone-to-app/create-ncco/swift

2020-08-27 11:46 UTC, pardel approved these changes
LGTM

2020-08-27 11:46 UTC, merged