Devx 3858 app tp app
Nexmo/nexmo-developer pull request #3139
Opened 2020-08-28 07:33 UTC by igorwojda

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2020-08-28 11:07 UTC, pardel requested changes

2020-08-28 11:07 UTC, pardel commented on config/tutorials/en/app-to-app/kotlin.yml
> +  - client-sdk/app-to-phone/create-ncco
you need the app-to-app NCCO

2020-08-28 11:07 UTC, pardel commented on config/tutorials/en/app-to-app/java.yml
> +  - client-sdk/app-to-phone/create-ncco
you'll need the app-to-app NCCO

2020-08-28 13:29 UTC, igorwojda commented
Fixed NCCO step and updated NCCO screenshots to match code snippet

2020-08-28 14:14 UTC, pardel requested changes
Looks good. Just couple of comments on server calling.

2020-08-28 14:14 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/make-call/java.md
> +    client.call(otherUserName, NexmoCallHandler.IN_APP, callListener);
We are moving to server calling so this will need to change to `NexmoCallHandler.SERVER`.

2020-08-28 14:14 UTC, pardel commented on _tutorials/en/client-sdk/app-to-app/make-call/java.md
> +Locate the `startAppToAppCall` method within the `MainViewModel` class and fill its body to enable call:
Can we add a note that only the Alice calling Bob scenario will work given the NCCO we're using?

2020-09-01 10:38 UTC, tbedford requested changes
Just one minor query.

2020-09-01 10:38 UTC, tbedford commented on _tutorials/en/client-sdk/app-to-app/receive-call/java.md
> +# Make a call
Topic appears to be receive call, but heading here is make call?

2020-09-01 11:18 UTC, igorwojda commented on _tutorials/en/client-sdk/app-to-app/receive-call/java.md
> +# Make a call
Good catch, fxed

2020-09-01 11:34 UTC, tbedford approved these changes

2020-09-01 11:34 UTC, merged