Update inbound-sms.md
Nexmo/nexmo-developer pull request #3220
Opened 2020-09-30 23:25 UTC by brianebert

Added 204 response option

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2020-10-01 07:06 UTC, mheap requested changes

2020-10-01 07:06 UTC, mheap commented on _documentation/en/messaging/sms/guides/inbound-sms.md
> +Any messages sent to one of your Nexmo virtual numbers are sent to your webhook using a [GET] or [POST] request. When you receive a message on your webhook, you must send a `200 OK` or '204 No Conten
Could you replace the quotes with backticks to indicate that this is a literal response string?

2020-10-13 10:06 UTC, lukeocodes commented
@brianebert please make the changes or I'll be forced to close this PR

2020-10-13 16:54 UTC, brianebert commented
Mr. Olif,

Are you saying that if I don't change quotation marks to back ticks, or whatever you asked for, that you intend to close my pr without correcting the substance of your documentation error?

Go ahead and close my pr. I don't really care. You are a for profit organization communicating with a volunteer who noticed a problem and tried to help other nexmo users. I await an answer to my question. Please cc your manager.

BE

Get your free encrypted mail account at protonmail.com and your communications with Motia will be encrypted end to end.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Tuesday, October 13, 2020 5:06 AM, Luke Oliff <notifications@github.com> wrote:

> [@brianebert](https://github.com/brianebert) please make the changes or I'll be forced to close this PR
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/Nexmo/nexmo-developer/pull/3220#issuecomment-707636600), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AC3JL3FSWKA2BAUDOYBQQBTSKQRDJANCNFSM4R7WI2EQ).

2020-10-13 17:31 UTC, mheap commented
Hi Brian,

Thanks for your interest in improving our docs. Your current proposed change would result in our tooling trying to translate `204 No Contact` as it's not designated as a literal string.

In line with your request, I'm closing your PR and will address the inconsistency that you've identified personally to make sure that our audience has all the information.

Cheers, Michael

2020-10-13 17:31 UTC, closed without merging