Add custom object for facebook message template
Nexmo/nexmo-developer pull request #3241
Opened 2020-10-06 16:14 UTC by chilupa

## Description

Added `$CUSTOM_OBJECT` ( Sending Media using Facebook )  URL in facebook message template

2020-12-22 19:24 UTC, mheap requested changes

2020-12-22 19:24 UTC, mheap commented on _documentation/en/messages/concepts/custom-objects.md
> +    "message": {
This isn't quite true. It needs testing, but I believe that it would be more like the following:



```json
{
  "from": {
    "type": "messenger",
    "id": $FB_SENDER_ID
  },
  "to": {
    "type": "messenger",
    "id": $FB_RECIPIENT_ID
  },
  "message": {
    "content": {
      "type": "custom",
      "custom": {
	    "attachment": {
	      "type": "template",
	      "payload": {
	        "template_type": "media",
	        "elements": [{
	          "media_type": "<image|video>",
	          "url": "<FACEBOOK_URL>"
  	        }]
	      }
	    }
      }
    }
  }
}
```

2020-12-23 14:50 UTC, bencgreenberg commented
👋🏻 Who would like to be responsible in moving this to the finish line or deciding what to do with it? @slorello89, as its Messages API, would you like to take a look at it and wrap it up?

2021-02-24 09:14 UTC, bencgreenberg commented
As it's been stale for a few months, I'm closing this PR.

2021-02-24 09:14 UTC, closed without merging