interactive voice response using nodejs
Nexmo/nexmo-developer pull request #3244
Opened 2020-10-07 01:15 UTC by spiritbro1

## Description

i create a simple tutorial of interactive voice response using nodejs

## Deploy Notes

nothing

2020-10-08 15:04 UTC, marklewin requested changes
This is a great start @spiritbro1 . A couple of things though ... Each step should be a separate markdown file in a tutorial directory beneath a product directory. See how we've done it in the `_tutorials/en/client-sdk/app-to-app` directory. So, you'll need to create a new directory structure (`_tutorials/en/voice-api/ivr-php`) and put the steps in there and link to them from your `config\tutorials\ivr-php.md` file. Hope that makes sense!

2020-10-08 16:41 UTC, spiritbro1 commented
hello yeah thats why it is still a draft coz it's still in progress

On Thu, Oct 8, 2020, 10:04 PM Mark Lewin <notifications@github.com> wrote:

> *@marklewin* requested changes on this pull request.
>
> This is a great start @spiritbro1 <https://github.com/spiritbro1> . A
> couple of things though ... Each step should be a separate markdown file in
> a tutorial directory beneath a product directory. See how we've done it in
> the _tutorials/en/client-sdk/app-to-app directory. So, you'll need to
> create a new directory structure (_tutorials/en/voice-api/ivr-php) and
> put the steps in there and link to them from your
> config\tutorials\ivr-php.md file. Hope that makes sense!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexmo/nexmo-developer/pull/3244#pullrequestreview-504882132>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5B4AMJJOSRFZ3L2HYSWFTSJXIILANCNFSM4SGXWILQ>
> .
>

2020-10-10 01:41 UTC, spiritbro1 commented
mr. @marklewin please help me i don't understand this error what should i do? ![Screenshot_2020-10-10-08-40-00-551_com.android.chrome.jpg](https://user-images.githubusercontent.com/62529025/95642693-575d2a00-0ad4-11eb-81b1-276aa77347a6.jpg)

2020-10-11 23:54 UTC, spiritbro1 commented
![image](https://user-images.githubusercontent.com/62529025/95693679-beefb280-0c57-11eb-96cd-d4d6face6ddf.png)

done @marklewin please review

2020-10-14 09:23 UTC, marklewin commented
Thanks for your contribution @spiritbro1 - I will be reviewing this today

2020-10-14 09:25 UTC, spiritbro1 commented
you're welcome, waiting for your review i hope its good ☺️

On Wed, Oct 14, 2020, 4:23 PM Mark Lewin <notifications@github.com> wrote:

> Thanks for your contribution @spiritbro1 <https://github.com/spiritbro1>
> - I will be reviewing this today
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexmo/nexmo-developer/pull/3244#issuecomment-708277740>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5B4ALSRATHNZTUGYBHY7TSKVUZ5ANCNFSM4SGXWILQ>
> .
>

2020-10-14 15:47 UTC, marklewin commented
> you're welcome, waiting for your review i hope its good ☺️

Hi @spiritbro1 , not going to get around to this today I'm afraid. It looks good though... I'll have a few suggestions for edits in a day or two but certainly no show-stoppers!

2020-10-14 17:43 UTC, spiritbro1 commented
alright thanks for the feedback it's okay i will wait take your time

On Wed, Oct 14, 2020, 10:47 PM Mark Lewin <notifications@github.com> wrote:

> you're welcome, waiting for your review i hope its good ☺️
>
> Hi @spiritbro1 <https://github.com/spiritbro1> , not going to get around
> to this today I'm afraid. It looks good though... I'll have a few
> suggestions for edits in a day or two but certainly no show-stoppers!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexmo/nexmo-developer/pull/3244#issuecomment-708491078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5B4AP2ZS2AXGN4APRDSHTSKXBYVANCNFSM4SGXWILQ>
> .
>

2020-10-20 11:00 UTC, marklewin requested changes
Great start, but please look at my comments and make the required changes before resubmitting

2020-10-20 11:08 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/setting-up-for-ivr.md
> +* [Learn how to use `vercel`](https://vercel.com/docs)
fixed in 4e037526d8db40ff0a2bbc6a03f280c1ee15d7f1

2020-10-20 11:08 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +> If you're using vercel, it will generates a URL. You can also set your own domain at vercel. It might also be useful to know that there is a `nexmo app:update` command if you need update the URLs y
where should i describe vercel below ```vercel login``` word?

2020-10-20 11:10 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +In the project directory, run vercel command to login to your vercel account:
what do you mean code format? like this 

`vercel` using ` ?

2020-10-20 11:11 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +> If you're using vercel, it will generates a URL. You can also set your own domain at vercel. It might also be useful to know that there is a `nexmo app:update` command if you need update the URLs y
fixed in 2f2755c1168eb0aedce7cb973c802ad8ec419b0c

2020-10-20 11:14 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/respond-to-user-input.md
> +After the user has provided input, Nexmo sends a webhook to the `eventUrl` defined in the `input`. Since we set the `eventUrl` to `/search`, our code routes the request to `searchAction`. The request
fixed in 41b5c6c4e38f73a75cd520af295c77682ec31ae3

2020-10-21 05:57 UTC, spiritbro1 commented
@marklewin please review again

2020-10-22 10:02 UTC, marklewin requested changes
Getting there! Thanks for all your efforts.

2020-10-22 10:02 UTC, marklewin commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +> If you're using vercel, it will generate a URL. You can also set your own domain at vercel. It might also be useful to know that there is a `nexmo app:update` command if you need update the URLs yo
You need to generate the URL before you create the application and configure webhooks

2020-10-22 11:27 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +> If you're using vercel, it will generate a URL. You can also set your own domain at vercel. It might also be useful to know that there is a `nexmo app:update` command if you need update the URLs yo
i don't understand what need to be changed here? that is exactly what i mean when you deploy my application to vercel it will generate url

2020-10-22 11:29 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +In the project directory, run vercel command to login to your vercel account:
fixed

2020-10-22 11:31 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/create-a-voice-application.md
> +You can use Nexmo CLI to create an application for Voice API by using the following command and replacing the `YOUR_URL` segments with the URL of your own application:
where should i write that?

2020-10-22 11:32 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/buy-a-phone-number.md
> +Now we can set up the phone number to point to the application you created earlier.
fixed

2020-10-22 11:33 UTC, spiritbro1 commented on _tutorials/en/voice-api/ivr-node/link-phone-number-to-the-nexmo-application.md
> +## Link phone numbers to the Nexmo Application
i don't understand please elaborate what do you want me to rewrote here?

2020-10-22 11:34 UTC, spiritbro1 commented
@marklewin please review again

2020-10-26 16:18 UTC, marklewin commented on _tutorials/en/voice-api/ivr-node/try-it-yourself.md
> +> If you're using vercel, it will generate a URL. You can also set your own domain at vercel. It might also be useful to know that there is a `nexmo app:update` command if you need update the URLs yo
In step 4, you tell readers to replace the URL with the one generated by Vercel, but you don't explain how to receive those URLs until step 7.

Please, in Step 4, tell them to enter `example.com/answer` as `example.com/event` and tell them that they will replace those URLs with the ones generated by vercel in a later step.

In Step 7, show them how to create those URLs and use the [CLI `app:update`](Create a Voice Application) to replace those dummy URLs with the ones from Vercel.

2020-10-26 23:57 UTC, closed without merging