adding tutorial for sending an SMS with asp.net
Nexmo/nexmo-developer pull request #3254
Opened 2020-10-08 14:00 UTC by slorello89

## Description

This creates a new ADP tutorial formatted tutorial for sending an SMS with ASP.NET Core, removing its dependency on the blog post

2020-10-08 14:44 UTC, marklewin requested changes
Looking good. Fixed some spelling issues that were breaking the build and also suggested some language changes.

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/create-sms-csproj.md
> +In the terminal navigate to your source directory and run the following command:
I think 'source' here might be confusing. It's the directory where they keep their code and nothing .NET-specific, right?

Perhaps just say something like: "In your terminal, execute the following command. This creates the `VonageSms` directory, which contains the starting point for your MVC application".

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/install-vonage-dotnet.md
> +In your console, navigate into the `VonageSms` and run the following command:
```suggestion
Change into the `VonageSms` directory that you created in the preceding step, and execute the following command:
```

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/install-vonage-dotnet.md
> +You can now open the `VonageSms.csproj` file in Visual Studio. Alternatively you can open this whole folder in Visual Studio Code, however note that if you use VS Code you may need to take care of so
I'd move the whole "Alternatively" thing into a "note":

```suggestion
You can now open the `VonageSms.csproj` file in Visual Studio. 

> **Note**: This tutorial assumes that you are using Visual Studio. Alternatively, you could open the `VonageSms` folder in Visual Studio Code or another editor, but you might have to create some of the scaffolding that Visual Studio generates for you.
```

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/create-send-sms-model.md
> +We are going to to be following the typical MVC pattern, so we'll start with the 'M' which stands for Model. In visual studio add a new file to the `Models` folder called `SmsModel.cs`. Add a using s
```suggestion
We are going to to be following the typical MVC pattern, so we'll start with the 'M' which stands for Model. In Visual Studio, add a new file to the `Models` folder called `SmsModel.cs`. Insert a `using` statement for `System.ComponentModel.DataAnnotations` at the top of this file and add the following code to it:
```

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/create-send-sms-view.md
> +Add a new folder under `Views` called `Sms`, in there add a file `index.cshtml` and add the following code to it:
```suggestion
Create a new folder under `Views` called `Sms`. Within `Sms`, add a file called `index.cshtml` that contains the following code:
```

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/add-sms-controller.md
> +Add using statements for `Vonage.Messaging`, `Vonage.Request`, and `Microsoft.Extensions.Configuration` at the top of this file.
```suggestion
Add `using` statements for `Vonage.Messaging`, `Vonage.Request`, and `Microsoft.Extensions.Configuration` at the top of this file.
```

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/add-sms-controller.md
> +Dependency inject an `IConfiguration` object via the constructor like so:
Is there a better way of saying this, at least in the heading?

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/sms-api/add-sms-controller.md
> +Next add a Send SMS Action to the controller:
```suggestion
Next, add a Send SMS Action to the controller:
```

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/configure-aspdotnet-app.md
> +```text
If this isn't sample code, I don't think we should be presenting it as such? Perhaps either show an extract from `appsettings.json` (with dummy values for key and secret, natch) or present it like this:

"Open your `appsettings.json` file and add the following two fields to it:

* `VONAGE_API_KEY`: Your API key
* `VONAGE_API_SECRET`: Your API secret

You can find your API key and secret in the [Developer Dashboard]()https://dashboard.nexmo.com/)"

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/run-dotnet-app.md
> +In your console navigate to the `csproj` directory and run the command `dotnet run`. This will start the application up on `http://localhost:5000`. Open that URL in your browser.
Maybe use "execute" here instead of "run", so that we don't have the word "run" twice in the same sentence.

Perhaps you could explain what will happen when they open the URL?

2020-10-08 14:44 UTC, marklewin commented on _tutorials/en/run-dotnet-app.md
> +In your console navigate to the `csproj` directory and run the command `dotnet run`. This will start the application up on `http://localhost:5000`. Open that URL in your browser.
Also, we normally have a final "What's next?" step in tutorials, to point people at other resources, etc. See http://localhost:3000/messaging/sms/tutorials/send-sms-with-flask/conclusion for an example.

2020-10-08 17:41 UTC, slorello89 commented on _tutorials/en/sms-api/add-sms-controller.md
> +Dependency inject an `IConfiguration` object via the constructor like so:
Dependency injection is the typical term you'd use to describe this (it's pervasive for .NET devs) - I dropped the Dependency and the I from the heading

2020-10-08 17:41 UTC, slorello89 commented on _tutorials/en/sms-api/create-sms-csproj.md
> +In the terminal navigate to your source directory and run the following command:
Fixed

2020-10-08 17:42 UTC, slorello89 commented on _tutorials/en/sms-api/install-vonage-dotnet.md
> +In your console, navigate into the `VonageSms` and run the following command:
Fixed

2020-10-08 17:42 UTC, slorello89 commented on _tutorials/en/sms-api/install-vonage-dotnet.md
> +You can now open the `VonageSms.csproj` file in Visual Studio. Alternatively you can open this whole folder in Visual Studio Code, however note that if you use VS Code you may need to take care of so
agreed, moved it to a note

2020-10-08 17:42 UTC, slorello89 commented on _tutorials/en/sms-api/create-send-sms-model.md
> +We are going to to be following the typical MVC pattern, so we'll start with the 'M' which stands for Model. In visual studio add a new file to the `Models` folder called `SmsModel.cs`. Add a using s
fixed

2020-10-08 17:42 UTC, slorello89 commented on _tutorials/en/sms-api/create-send-sms-view.md
> +Add a new folder under `Views` called `Sms`, in there add a file `index.cshtml` and add the following code to it:
done

2020-10-08 17:43 UTC, slorello89 commented on _tutorials/en/sms-api/add-sms-controller.md
> +Add using statements for `Vonage.Messaging`, `Vonage.Request`, and `Microsoft.Extensions.Configuration` at the top of this file.
added

2020-10-08 17:43 UTC, slorello89 commented on _tutorials/en/configure-aspdotnet-app.md
> +```text
fixed

2020-10-08 17:43 UTC, slorello89 commented on _tutorials/en/run-dotnet-app.md
> +In your console navigate to the `csproj` directory and run the command `dotnet run`. This will start the application up on `http://localhost:5000`. Open that URL in your browser.
switched execute and run, added next steps section to the config.

2020-10-09 09:34 UTC, marklewin requested changes
Suggestions for the "next steps" task

2020-10-09 09:34 UTC, marklewin commented on config/tutorials/en/send-sms-with-dotnet.yml
> +      See [SMS API documentation](/messaging/sms/overview).
```suggestion
      See the [SMS API documentation](/messaging/sms/overview).
```

2020-10-09 09:34 UTC, marklewin commented on config/tutorials/en/send-sms-with-dotnet.yml
> +      In the meantime for more information on our APIs including:
Can we point at other SMS-related links here instead?

```suggestion
You can do a lot more with the SMS API. Find out more:

- [Read the SMS API documentation](https://developer.nexmo.com/messaging/sms/overview)
- [View the API reference](https://developer.nexmo.com/api/sms)
- [Receive an SMS](https://developer.nexmo.com/messaging/sms/code-snippets/receiving-an-sms/dotnet)
- [Get a delivery receipt](https://developer.nexmo.com/messaging/sms/code-snippets/delivery-receipts/dotnet)
```

2020-10-09 16:59 UTC, marklewin approved these changes
Great, thanks @slorello89

2020-10-09 17:43 UTC, merged