fixing dependency names for .NET PHP and python
Nexmo/nexmo-developer pull request #3258
Opened 2020-10-09 18:10 UTC by slorello89

## Description

Some of the code snippets for .NET / PHP / and Python were displaying the wrong dependency - updating

2020-10-09 18:16 UTC, dragonmantank commented
PHP ones look good after pushing a fix that missed a few. Do we need to check the other three languages as well?

2020-10-09 18:21 UTC, slorello89 commented
Spot check only showed those three with issues - worth a look.

2020-10-09 20:44 UTC, slorello89 commented
@dragonmantank - I did a search of the entire `_examples` directory and replaced every reference to a nexmo package inside of a yml file

2020-10-16 09:17 UTC, mheap commented
Is https://github.com/Nexmo/nexmo-developer/blob/master/config/code_languages.yml#L55 still correct? Or is the new package name `Vonage`?

2020-10-22 12:55 UTC, dragonmantank requested changes
Looks like PHP just had one incorrect one, otherwise the PHP snippets look good

2020-10-22 12:55 UTC, dragonmantank commented on _examples/messaging/sms/send-an-sms-with-unicode/php.yml
> +    - vonage
This should be `vonage/client`

2020-10-22 12:57 UTC, slorello89 commented on _examples/messaging/sms/send-an-sms-with-unicode/php.yml
> +    - vonage
fixed

2020-10-22 15:19 UTC, dragonmantank approved these changes
Good for my snippets

2020-10-26 16:18 UTC, tbedford commented
@dragonmantank Can we merge?

2020-10-28 14:02 UTC, tbedford commented
@lornajane @superdiana - are we good to go on this one?

2020-10-29 10:53 UTC, lornajane commented
I'm not sure what I'm doing here :) I can't see that these changes would cause a problem, but I don't think they caught everything.

2020-10-29 10:54 UTC, lornajane approved these changes
Definitely a bunch of improvements here! Thanks people

2020-10-29 10:54 UTC, merged