Smartling Translations Download Workflow
Nexmo/nexmo-developer pull request #3291
Opened 2020-10-19 18:10 UTC by bencgreenberg

## Description

Check for new Smartling completed translations on a schedule, download them and raise a pull request with the new files.

2020-10-26 18:42 UTC, bencgreenberg commented
@fabianrbz, Something to consider when reviewing this is the way we currently initialize `TranslatorCoordinator` now with passing in a `frequency` integer, does that make sense? Shouldn't we dynamically generate it from either the number provided in the markdown file or in the product config, if the former is missing? This is currently unresolved and right now the Rake task will not work because it expects a manual `frequency` input, but considering it this afternoon, I think this needs to be refactored. What do you think?

2020-11-03 12:29 UTC, bencgreenberg commented on .github/workflows/smartling_uploader.yml
> +        RAILS_ENV=test bundle exec nexmo-developer --docs=. --rake-smartling-upload ${{matrix}}
@fabianrbz - In the [upload rake task](https://github.com/Nexmo/station/pull/277/files#diff-e8238f8b64f6a3f747c678954ba51f53e0a2ef22d7d494528228e881f18f81f7R56) there is an argument for frequency, which as we know is used to find files with that translation frequency either specified in the markdown metadata for that file and if not there, in the products config.

How might we specify that in the workflow here?

2020-11-24 13:33 UTC, bencgreenberg commented on .github/workflows/smartling_uploader_15_days.yml
> +name: Smartling Uploader for Files Changed within 1 Day
```suggestion
name: Smartling Uploader for Files Changed within 15 Days
```

2020-11-24 13:33 UTC, bencgreenberg commented on .github/workflows/smartling_uploader_30_days.yml
> +name: Smartling Uploader for Files Changed within 1 Day
```suggestion
name: Smartling Uploader for Files Changed within 30 Days
```

2020-11-27 08:14 UTC, fabianrbz requested changes

2020-11-27 08:14 UTC, fabianrbz commented on .github/workflows/smartling_uploader_180_days.yml
> +    branches:
@bencgreenberg this should run on a schedule, every 180 days

2020-11-27 08:14 UTC, fabianrbz commented on .github/workflows/smartling_uploader_5_days.yml
> +      - master
same here but 5 days

2020-11-27 09:01 UTC, bencgreenberg commented on .github/workflows/smartling_uploader_5_days.yml
> +      - master
Done

2020-11-27 09:01 UTC, bencgreenberg commented on .github/workflows/smartling_uploader_180_days.yml
> +    branches:
Done

2020-11-27 14:04 UTC, fabianrbz approved these changes

2020-11-30 07:46 UTC, merged