Add first Go snippets
Nexmo/nexmo-developer pull request #3294
Opened 2020-10-19 20:41 UTC by lornajane

## Description

Add the Go code snippets that we have so far to the developer portal. It seems like the platform also needs some changes though!

2020-10-19 20:41 UTC, lornajane commented
The Markdown Renderer also needs a fix so this PR depends on https://github.com/Nexmo/nexmo-markdown-renderer/pull/33

2020-10-21 09:42 UTC, lornajane commented
Also related: PR to add the Go logo to Station: https://github.com/Nexmo/station/pull/376

2020-10-21 09:43 UTC, lornajane commented
Next up is the release for markdown renderer (and then for station, after which I can update this branch) - track that work here https://github.com/Nexmo/nexmo-markdown-renderer/pull/34

2020-11-16 10:21 UTC, lornajane commented
@fabianrbz Thanks for the updates. I don't think this is ready to merge though since it is missing the syntax highlight - or should I resolve the conflicts, get it reviewed, and we can get it prettier at some future time?

2020-11-16 10:25 UTC, fabianrbz commented
@lornajane we should rebase this and get it ready, volta's npm package will be released at some point this week, but we could  merge this without it. Totally up to you :D

2020-11-16 10:46 UTC, lornajane commented
Thanks! I think I'll add the other snippets first, then release and the syntax highlight can catch us up whenever.

2020-11-17 11:31 UTC, bencgreenberg commented
It's looking good in the review app, and once the syntax highlighter is updated,  it'll look even better. Way to go, Lorna! Excited to see some Go snippets in ADP!

2020-11-17 11:44 UTC, lornajane commented
@bencgreenberg I was just namedropping you! @GregHolmes has some more SMS snippets incoming so we're going to add the whole SMS set and then merge. I'm excited too!!

2020-11-20 18:03 UTC, lornajane commented
I think we're close! Tagged a few of you as reviewers :) Thanks @GregHolmes for the work on the snippets

2020-11-23 09:43 UTC, marklewin approved these changes
Checked in review app and they look great :) Looking forward to the syntax highlighting but otherwise these look good to Go (sorry 😬 ). Well done team!

2020-11-23 09:49 UTC, fabianrbz requested changes

2020-11-23 09:49 UTC, fabianrbz commented on _examples/messaging/sms/send-an-sms-with-unicode/go.yml
> +  - Vonage/vonage-go-sdk
we need to prepend `github.com/` to this, otherwise, we get the following error `import path does not begin with hostname`

2020-11-23 09:49 UTC, fabianrbz commented on _examples/messaging/sms/send-an-sms/go.yml
> +  - Vonage/vonage-go-sdk
same here

2020-11-23 11:03 UTC, fabianrbz commented
They look really good! I left a few comments, also I know it's not related to this PR but it would be nice to include it here.
Looks like the Dashboard changed its UI, so can we update:
`public/screenshots/smsDeliveryReceiptsWebhook.png` and 
`public/screenshots/smsInboundWebhook.png`?

2020-11-23 11:21 UTC, mheap commented
Is it worth setting `unindent: true` for Go as most snippets will be inside a `main` block?

e.g. https://github.com/Nexmo/nexmo-developer/blob/master/config/code_languages.yml#L42

2020-11-24 09:40 UTC, lornajane commented on _examples/messaging/sms/send-an-sms/go.yml
> +  - Vonage/vonage-go-sdk
Good catch, thanks!

2020-11-24 09:40 UTC, lornajane commented on _examples/messaging/sms/send-an-sms-with-unicode/go.yml
> +  - Vonage/vonage-go-sdk
Good catch, thanks!

2020-11-24 09:41 UTC, lornajane commented
Good catch @fabianrbz and thanks for the tip @mheap (I couldn't find docs on the code language config so I improvised!). I think we might almost be there now, lucky that Mark already covered the necessary Go puns ;)

2020-11-26 10:31 UTC, lornajane commented
Is anything else needed here? We've got the next batch of snippets to add when this one is in ....

2020-11-27 08:09 UTC, fabianrbz commented
@lornajane I need to release volta's update first, which was released yesterday

2020-12-01 17:08 UTC, lornajane commented on _examples/messaging/sms/send-an-sms/go.yml
> +    source: .repos/vonage/vonage-go-code-snippets/sms/send-sms.go
Can you clarify the point about the sections and the line numbers? I followed the pattern of the other libraries which do not have the include/require/import lines in the client section but do show how to initialise the client and add the creds. I'll push a commit changing the case of the package name though, good catch! /cc @GregHolmes who might need to keep an eye on this while I'm out of the office

2020-12-03 07:38 UTC, fabianrbz commented on _examples/messaging/sms/send-an-sms/go.yml
> +    source: .repos/vonage/vonage-go-code-snippets/sms/send-sms.go
@lornajane oh well, looks like we do things differently for different programming languages/code snippets, so I'm ok with this if you are.

2020-12-03 07:38 UTC, fabianrbz commented
Volta's PR was merged already, so we can release this

2020-12-03 13:14 UTC, mheap commented
Flagging as do not merge until we have a strategy for maintenance and extending the Go SDK to additional products

2020-12-03 13:56 UTC, bencgreenberg commented
> Flagging as do not merge until we have a strategy for maintenance and extending the Go SDK to additional products

That's a good point, Michael. I also know we try to avoid PRs going stale. Do you have a sense of timeline for that conversation? Will this PR be sitting here for a while?

2020-12-03 13:58 UTC, mheap commented
It'll wait until we have a strategy for the Go SDK in 2021

2021-02-25 07:55 UTC, bencgreenberg commented
Should we keep this PR open or can we reopen when this is ready at some point this year as indicated earlier? @dragonmantank, what do you think?

2021-02-25 11:25 UTC, marklewin commented
Would be great to keep open, because I'm planning to add a few new snippets
this week/early next week.

On Thu, 25 Feb 2021 at 07:55, Ben Greenberg <notifications@github.com>
wrote:

> Should we keep this PR open or can we reopen when this is ready at some
> point this year as indicated earlier? @dragonmantank
> <https://github.com/dragonmantank>, what do you think?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexmo/nexmo-developer/pull/3294#issuecomment-785697444>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEKVV47RUS2J3GH25AJUGFLTAX67TANCNFSM4SWVATWQ>
> .
>

2021-02-25 11:27 UTC, bencgreenberg commented
> Would be great to keep open, because I'm planning to add a few new snippets this week/early next week.

Sounds good to me, just wanted someone to confirm, thanks!

2021-02-25 14:32 UTC, GregHolmes commented
I have spoken to various people and it appears we will not be adding the Go code snippets to the NDP in 2021. There is a possibility for this to be added in 2022. Rather than keeping a PR open for this length of time, we've decided to close the pull request, but keep the branch active. If you wish to add any more snippets to this branch, please feel free to.

I'll be working at maintaining the branch to ensure that it doesn't stagnate and is ready for review as soon as the chance arrives.

2021-02-25 14:32 UTC, closed without merging