Adding stream audio with dotnet tutorial
Nexmo/nexmo-developer pull request #3297
Opened 2020-10-20 20:21 UTC by slorello89

## Description

Adding stream audio with .NET tutorial

2020-10-21 15:22 UTC, niati commented
@slorello89 one minor issue I observed - the MD file for Step 8 (add-voice-view.md) is missing a page heading.

2020-10-21 16:00 UTC, marklewin requested changes
Generally looks great, just a few stylistic suggestions

2020-10-21 16:00 UTC, marklewin commented on config/tutorials/en/play-audio-into-call-dotnet.yml
> +    - [Check out our NCCO Reference](https://developer.nexmo.com/voice/voice-api/ncco-reference)
```suggestion
    - [NCCO Reference](https://developer.nexmo.com/voice/voice-api/ncco-reference)
```

2020-10-21 16:00 UTC, marklewin commented on config/tutorials/en/play-audio-into-call-dotnet.yml
> +    Find out more about the Capabilities of the Vonage Voice API:
```suggestion
    Find out more about the capabilities of the Vonage Voice API:
```

2020-10-21 16:22 UTC, slorello89 commented on _tutorials/en/voice-api/create-voice-csproj.md
> +To start, we will create an SMS `csproj` file. We will have it not configure kestrel for https for testing purposes.
I think my phraseology is correct here. we are going to be using kestrel, without https

2020-10-21 16:26 UTC, slorello89 commented on _tutorials/en/voice-api/create-voice-csproj.md
> +To start, we will create an SMS `csproj` file. We will have it not configure kestrel for https for testing purposes.
@marklewin - trying to split the difference here - what do you think of the new phrasing?

2020-10-21 16:58 UTC, tbedford commented
General minor note: who is "we"? If you say "we create..." is that something Vonage does for the user, or does the user do it? If you say "You create" there is no ambiguity.

2020-10-21 19:46 UTC, slorello89 commented
@tbedford good point - I've removed all of the plural first persons and replaced them with second person (or no pronoun where possible)

2020-10-22 09:03 UTC, marklewin commented on _tutorials/en/voice-api/create-voice-csproj.md
> +To start, we will create an SMS `csproj` file. We will have it not configure kestrel for https for testing purposes.
@slorello89 My bad! It still sounds a bit clumsy to me though: "You will have it not configure kestrel for https for testing purposes."

Would this work? "To make testing easier, configure Kestrel with HTTPS disabled." (I note that Kestrel is a proper noun with a capital K generally on the interwebs and think we should do the same.)

2020-10-22 09:22 UTC, marklewin requested changes
Just a few further (but minor) suggestions @slorello89 , although please check that "SMS" heading in `/voice/voice-api/tutorials/play-audio-into-call-dotnet/voice-api/create-voice-csproj`

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/add-receive-call-route-stream-audio.md
> +You will now provide an [answer webhook](/voice/voice-api/webhook-reference#answer-webhook) so that when you receive an inbound call on your virtual number, the Vonage API platform will notify us on
```suggestion
You will now provide an [answer webhook](/voice/voice-api/webhook-reference#answer-webhook) so that when you receive an inbound call on your virtual number, the Vonage API platform will notify you on that webhook via an HTTP request.
```

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-voice-csproj.md
> +# Create the SMS Project File
Is this a copy/paste error, or does SMS have meaning in .NET that I don't understand?! This is a VAPI tutorial, right?

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-voice-csproj.md
> +To start, you will create an SMS `csproj` file. You will have it not configure kestrel for https for testing purposes.
SMS again?

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-voice-csproj.md
> +In your terminal, execute the following command.
```suggestion
In your terminal, execute the following command:
```

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-vonage-application.md
> +There are two alternative methods for creating a Voice application:
There aren't really two alternatives (alternatives to what?), so probably best to just say "There are two methods..."

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-vonage-application.md
> +To create your application using the Nexmo CLI, enter the following command into the shell replacing `NGROK_HOST_NAME` with the ngrok host that you got when you setup ngrok:
```suggestion
To create your application using the Nexmo CLI, enter the following command into the shell replacing `NGROK_HOST_NAME` with the ngrok host that you got when you set up ngrok:
```
(setup is a noun, set up is the verb form)

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-vonage-application.md
> +This creates a Nexmo application with a voice [capability](/application/overview#capabilities), with the webhook URLs configured as specified, and generate a private key file `private.key` - save thi
```suggestion
This command creates a Vonage Application with Voice [capability](/application/overview#capabilities). It  configures the Application with your answer and event webhook URLs and generates a private key file `private.key`, which you should save in your project directory.

The command returns a unique Application ID. Use this Application ID to link your Vonage virtual number to your Application by executing the following:

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-vonage-application.md
> +6. In the **Event URL** box, enter the URL for your call status webhooks, for example, `http://example.com/webhooks/events`.
```suggestion
6. In the **Event URL** box, enter the URL for your call status webhook, for example, `http://example.com/webhooks/events`.
```

2020-10-22 09:22 UTC, marklewin commented on _tutorials/en/voice-api/create-vonage-application.md
> +8. You are now taken to the next step of the Create Application procedure where you can link a Vonage number to the application, link your Vonage virtual number to the application.
```suggestion
8. You are now taken to the next step of the Create Application procedure where you should link your Vonage number to the application.
```

2020-10-22 12:51 UTC, slorello89 commented on _tutorials/en/voice-api/create-voice-csproj.md
> +# Create the SMS Project File
Nope you're totally right - copy paste issue

2020-10-22 12:54 UTC, slorello89 commented on _tutorials/en/voice-api/create-vonage-application.md
> +There are two alternative methods for creating a Voice application:
valid point

2020-10-22 12:54 UTC, slorello89 commented on _tutorials/en/voice-api/create-voice-csproj.md
> +To start, you will create an SMS `csproj` file. You will have it not configure kestrel for https for testing purposes.
copy/paste issue

2020-10-22 16:03 UTC, marklewin approved these changes
LGTM!

2020-10-22 16:09 UTC, merged