CCI Guide
Nexmo/nexmo-developer pull request #3301
Opened 2020-10-23 18:36 UTC by vshisterov

## Description

New Contact Center Intelligence guide added in the scope of the [partnership with Amazon](https://aws.amazon.com/machine-learning/contact-center-intelligence/).

2020-10-23 18:48 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +Voice API, together with partner solutions, empowers you with the cutting-edge technology of phone call processing, assistance, and analytics, which is extremely helpful for Contact Center cases. Doe
```suggestion
The Vonage Voice API, together with partner solutions, empowers you with the cutting-edge technology of phone call processing, assistance, and analytics, which is extremely helpful for Contact Center cases. It does not matter if you’re building a Contact Center solution from scratch, or already have a legacy CC/PBX solution which you want to extend with modern features and workflows such as AI voice assistants or sentiment analysis, Voice API and partner solutions are ideal to assist you.
```

2020-10-23 18:48 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +# Contact Center Intelligence
```suggestion
# Contact Center Intelligence

```

2020-10-23 18:48 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +There are three groups of contact center oriented use-cases where Voice API can help:
```suggestion
There are three groups of contact center oriented use-cases where the Voice API can help:
```

2020-10-23 18:49 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +* **Self-service**. Offer more choice with customers having the options to select self-service for faster resolutions to low complexity inquiries with smart FAQs.
```suggestion
* **Self-service**. Offer more choice with customers having the option to select self-service for faster resolutions to low complexity inquiries with smart FAQs.
```

2020-10-23 18:49 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +* **Real-time analytics and agent assist**. Empower agents with real time insights and in-call tools delivered through AI engines.  Provide feedback to the customer’s real time call experience and po
```suggestion
* **Real-time analytics and agent assist**. Empower agents with real-time insights and in-call tools delivered through AI engines.  Provide feedback to the customer’s real-time call experience and populate key information so agents can provide a top-level customer experience.
```

2020-10-23 18:50 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +* **Post-call analytics**. Extract meaningful insights from recorded calls or chats to help agents and supervisors better understand conversations with customers, uncovering patterns and quality issu
```suggestion
* **Post-call analytics**. Extract meaningful insights from recorded calls or chats to help agents and supervisors better understand conversations with customers, uncovering patterns, and quality issues so they can resolve issues faster and ultimately improve the overall customer experience. Post-call speech analytics dashboards, driving agent, and operational performance statistics, provide insights for managers, quality assurance personnel, and other leadership groups.
```

2020-10-23 18:50 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +For *self-service* cases, Voice API provides the following set of features:
```suggestion
For *self-service* cases, the Voice API provides the following set of features:
```

2020-10-23 18:51 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +With WebSockets, you can also easily embed any kind of real-time analytics into your contact center. With an NCCO [`connect`](/voice/voice-api/ncco-reference#connect) action, you can attach WebSocket
```suggestion
With WebSockets, you can also embed any kind of real-time analytics into your contact center. With an NCCO [`connect`](/voice/voice-api/ncco-reference#connect) action, you can attach WebSocket one-way (or two-way, depending on the case) stream to any inbound or outbound call and then pass the media to an analytics engine, such as [Amazon Transcribe](https://aws.amazon.com/transcribe/). You can further do a deeper analysis with [Amazon Comprehend](https://aws.amazon.com/comprehend/) to provide the agent with useful insights and real-time hints during the call.
```

2020-10-23 18:51 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +After the call is completed, it is likely you may want to keep the keynotes, as well as be able to search through the recordings. In order to do that, Voice API allows you to record every call or par
```suggestion
After the call is completed, it is likely you may want to keep the keynotes, as well as be able to search through the recordings. In order to do that, the Voice API allows you to record every call or part of the call so that you can store and analyze it. Learn how to do that with our [Transcribe a Recorded Call with Amazon Transcribe](/use-cases/trancribe-amazon-api) complete tutorial.
```

2020-10-23 18:52 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +### IVR
```suggestion
### IVR

```

2020-10-23 18:52 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +For the typical IVR case, the user is calling some PSTN (phone) number and interacts with the virtual operator by choosing the options via DTMF tones (key input) or just by saying the option (speech
```suggestion
For the typical IVR case, the user is calling a PSTN (phone) number and interacts with the virtual operator by choosing the options via DTMF tones (key input) or by saying the option (speech input). To build a solution like this, what is needed is a [Vonage virtual number](/numbers/overview) assigned to your [application](/application/overview), which interacts with the user through the Vonage Voice API platform by providing [NCCO](/voice/voice-api/guides/ncco) commands (actions) such as [`talk`](/voice/voice-api/ncco-reference#talk) for Text-to-Speech message and [`input`](/voice/voice-api/ncco-reference#input) for DTMF/speech input:
```

2020-10-23 18:53 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +Vonage encapsulates all the complexity of the carrier connections’ complexity, so all you need is to just buy a Vonage virtual number, assign it to your app, and implement HTTP request handlers ([web
```suggestion
Vonage encapsulates all the complexity of the carrier connections’ complexity, so all you need is to provision a Vonage virtual number, assign it to your app, and implement HTTP request handlers ([webhooks](/voice/voice-api/webhook-reference)) to instruct the Voice platform with the desired call control [actions](/voice/voice-api/ncco-reference). Building a simple IVR is this easy.
```

2020-10-23 18:53 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +Quite a similar approach can be used for voice notifications with or without IVR as a part of it. The difference is that now your app initiates the call with a simple [REST API](/api/voice#createCall
```suggestion
Quite a similar approach can be used for voice notifications with or without IVR as a part of it. The difference is that now your app initiates the call with a [REST API](/api/voice#createCall) (HTTP) request:
```

2020-10-23 18:54 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +As a step in your IVR flow, you may want to have an option to connect the user to your contact center agent. You can do this easily with [`connect`](/voice/voice-api/ncco-reference#connect) NCCO acti
```suggestion
As a step in your IVR flow, you may want to have an option to connect the user to your contact center agent. You can do this with the [`connect`](/voice/voice-api/ncco-reference#connect) NCCO action by either forwarding the call to a PSTN number or connecting it to the SIP endpoint of your contact center platform:
```

2020-10-23 18:55 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +Many contact center solutions require a way to receive context information regarding the currently processed call. A traditional way to send such data to the CC is by adding one or several custom SIP
```suggestion
Many contact center solutions require a way to receive context information regarding the currently processed call. A traditional way to send such data to the CC is by adding one or more custom SIP Headers with tokens to the SIP INVITE message. Generally, this token may be used to send the call to a specific group of specialized Agents. Some CC solutions may even use this token, for example, to automatically open a browser to the customer CRM page in the Agent’s computer, via the CTI, when they answer the call. 
```

2020-10-23 18:55 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +The transmission of one or several custom SIP Headers from the Voice platform to the CC is easily achievable using [`headers`](/voice/voice-api/ncco-reference#sip-the-sip-endpoint-to-connect-to) para
```suggestion
The transmission of one or more custom SIP Headers from the Voice platform to the CC is achievable using the [`headers`](/voice/voice-api/ncco-reference#sip-the-sip-endpoint-to-connect-to) parameter in the `connect` NCCO action.
```

2020-10-23 18:55 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +### Voice Bot
```suggestion
### Voice Bot

```

2020-10-23 18:56 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +If you want to enhance your IVR with natural language understanding (NLU), you may connect it to an AI service, such as [Amazon Lex](https://aws.amazon.com/lex/). Lex accepts both text and media (aud
```suggestion
If you want to enhance your IVR with natural language understanding (NLU), you may connect it to an AI service, such as [Amazon Lex](https://aws.amazon.com/lex/). Lex accepts both text and media (audio) and provides text and media output following the business logic you implement in your bot. In order to connect the telephony world with binary media processing services, you may use a WebSocket connection, supported by the Vonage Voice platform. To do that, include the [`connect` action](/voice/voice-api/ncco-reference#connect) with your app WebSocket URL as the endpoint into your NCCO - and the call will be immediately connected to your app with media flowing from the user and backward. Then you just need to pass the media frames to Lex and stream Lex responses back through the same connection:
```

2020-10-23 18:57 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/cci.md
> +Also, when your bot detects user intent to have a talk with a human agent, your application may send a [transfer](/voice/voice-api/code-snippets/transfer-a-call) request to Vonage API, and it will co
```suggestion
Furthermore, when your bot detects user intent to have a conversation with a human agent, your application may send a [transfer](/voice/voice-api/code-snippets/transfer-a-call) request to the Vonage API, and it will connect the user to your Contact Center:
```

2020-10-23 18:58 UTC, bencgreenberg commented
Looks good! I added some comments but would also be good to get the feedback from @marklewin or @tbedford on this as well.

2020-10-26 09:52 UTC, marklewin requested changes
This is great. I've just made a few minor stylistic suggestions in addition to those raised by @bencgreenberg

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +* **Post-call analytics**. Extract meaningful insights from recorded calls or chats to help agents and supervisors better understand conversations with customers, uncovering patterns and quality issu
"Post-call speech analytics dashboards, driving agent, and operational performance statistics," - I'd lose the comma after "agent"

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +With WebSockets, you can also easily embed any kind of real-time analytics into your contact center. With an NCCO [`connect`](/voice/voice-api/ncco-reference#connect) action, you can attach WebSocket
```suggestion
With WebSockets, you can also easily embed any kind of real-time analytics into your contact center. With an NCCO [`connect`](/voice/voice-api/ncco-reference#connect) action, you can attach WebSocket one-way (or two-way, depending on the case) stream to any inbound or outbound call and then pass the media to an analytics engine, such as [Amazon Transcribe](https://aws.amazon.com/transcribe/). You can perform a deeper analysis with [Amazon Comprehend](https://aws.amazon.com/comprehend/) to provide the agent with useful insights and real-time hints during the call.
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +Let’s take a closer look at the components of the solution you may want to build for each use case.
'Might' would be better than 'may' here. May implies that you have permission, where 'might' suggests that you have the option.

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +For the typical IVR case, the user is calling some PSTN (phone) number and interacts with the virtual operator by choosing the options via DTMF tones (key input) or just by saying the option (speech
```suggestion
For the typical IVR case, the user calls a PSTN (phone) number and interacts with the virtual operator by choosing the options via DTMF tones (key input) or just by saying the option (speech input). To build a solution like this, what is needed is a [Vonage virtual number](/numbers/overview) assigned to your [application](/application/overview), which interacts with the user through the Vonage Voice API platform by providing [NCCO](/voice/voice-api/guides/ncco) commands (actions) such as [`talk`](/voice/voice-api/ncco-reference#talk) for Text-to-Speech message and [`input`](/voice/voice-api/ncco-reference#input) for DTMF/speech input:
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +Vonage encapsulates all the complexity of the carrier connections’ complexity, so all you need is to just buy a Vonage virtual number, assign it to your app, and implement HTTP request handlers ([web
```suggestion
Vonage deals with the complexity of connecting the call, so all you need is to just buy a Vonage virtual number, assign it to your app, and implement HTTP request handlers ([webhooks](/voice/voice-api/webhook-reference)) to instruct the Voice platform with the desired call control [actions](/voice/voice-api/ncco-reference). Building a simple IVR is this easy.
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +Quite a similar approach can be used for voice notifications with or without IVR as a part of it. The difference is that now your app initiates the call with a simple [REST API](/api/voice#createCall
```suggestion
You can use similar approach can be used for voice notifications, with or without an IVR. The difference is that now your app initiates the call with a simple [REST API](/api/voice#createCall) (HTTP) request:
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +As a step in your IVR flow, you may want to have an option to connect the user to your contact center agent. You can do this easily with [`connect`](/voice/voice-api/ncco-reference#connect) NCCO acti
```suggestion
As a step in your IVR flow, you might want to be able to connect the user to your contact center agent. You can do this easily with [`connect`](/voice/voice-api/ncco-reference#connect) NCCO action by either forwarding the call to a PSTN number or connecting it to the SIP endpoint of your contact center platform:
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +Many contact center solutions require a way to receive context information regarding the currently processed call. A traditional way to send such data to the CC is by adding one or several custom SIP
```suggestion
Many contact center solutions require a way to receive context information regarding the currently processed call. A traditional way to send such data to the CC is by adding one or several custom SIP Headers with tokens to the SIP INVITE message. Generally, this token may be used to send the call to a specific group of specialized Agents. For example, some CC solutions can use this token to automatically open a browser to the customer CRM page in the Agent’s computer, via the CTI, when they answer the call. 
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +If you want to enhance your IVR with natural language understanding (NLU), you may connect it to an AI service, such as [Amazon Lex](https://aws.amazon.com/lex/). Lex accepts both text and media (aud
```suggestion
If you want to enhance your IVR with natural language understanding (NLU), you may connect it to an AI service, such as [Amazon Lex](https://aws.amazon.com/lex/). Lex accepts both text and media (audio) and provides text and media output following the business logic you implement in your bot. In order to connect telephony with binary media processing services, you could use a WebSocket connection, which is supported by the Vonage Voice platform. To do that, just include [`connect` action](/voice/voice-api/ncco-reference#connect) with your app WebSocket URL as the endpoint into your NCCO - and the call will be immediately connected to your app with media flowing to and from the user. Then you just need to pass the media frames to Lex and stream Lex responses back through the same connection:
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +To start quickly with implementation, clone the reference [Lex Connector](https://github.com/Nexmo/lex-connector) application, which has everything you need to connect the voice calls to your Lex bot
```suggestion
For a quick implementation, clone the reference [Lex Connector](https://github.com/Nexmo/lex-connector) application, which has everything you need to connect the voice calls to your Lex bot.
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +Provide full context of the bot conversation to your CC by connecting directly to your CC using SIP and custom SIP Headers to transmit the correlation information.
```suggestion
Provide full context of the bot conversation to your CC by connecting directly to your CC using SIP and custom SIP Headers to transmit the correlated information.
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +A quite similar approach can be used for real-time analysis of the conversation between the user and the agent: the user is connected to your contact center through the Vonage voice platform with the
```suggestion
Use a similar approach to perform real-time analysis of the conversation between the user and the agent: the user is connected to your contact center through the Vonage voice platform with the [`connect`](/voice/voice-api/ncco-reference#connect) action sent from your application, then another `connect`action is used to establish a [WebSocket](/voice/voice-api/guides/websockets) connection for sending the call media to your app, which then sends it to the analytics engine. Your application may then send the results of the analysis, such as sentiment or call hints to the agent to some widget on your agent's screen. You could embed this widget in your contact center user interface or use it in a standalone application:
```
(I'm guessing what you mean by "hints" here, but in any event think it would be useful to clarify)

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +Vonage Voice API allows you to easily [record](/voice/voice-api/guides/recording) the conversation or a part of the conversation, depending on your call flow and the use case. With [multichannel reco
```suggestion
The Vonage Voice API enables you to easily [record](/voice/voice-api/guides/recording) the conversation or a part of the conversation, depending on your call flow and the use case. Because you can record across [multiple channels](/voice/voice-api/guides/recording#multi-channel-recording), the audio file can be further processed by various analytics services. Check our detailed tutorial to learn how to [transcribe the recording using Amazon Transcribe](/use-cases/trancribe-amazon-api).
```

2020-10-26 09:52 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +* **Post-call analytics**. Extract meaningful insights from recorded calls or chats to help agents and supervisors better understand conversations with customers, uncovering patterns and quality issu
```suggestion
* **Post-call analytics**. Extract meaningful insights from recorded calls or chats to help agents and supervisors better understand conversations with customers. Uncover patterns and quality concerns so that they can resolve issues faster and ultimately improve the overall customer experience. Post-call speech analytics dashboards drive agent and operational performance statistics and provide insights for managers, quality assurance personnel, and other leadership groups.
```

2020-10-26 10:15 UTC, vshisterov reviewed
Thank you so much, @bencgreenberg and @marklewin ! I've applied all the suggestions, could you kindly review?

2020-10-26 12:46 UTC, vshisterov commented
Let me think a bit more about how to integrate our Vonage AI offering there as well...

2020-10-26 14:21 UTC, bencgreenberg commented
> Let me think a bit more about how to integrate our Vonage AI offering there as well...

Okay, let me know when you're ready for another review.

2020-10-27 11:58 UTC, vshisterov commented
I've added a couple of links to Vonage AI, can't be more specific at the moment. Please review one more time!

2020-10-27 13:46 UTC, marklewin requested changes
A couple of minor stylistic suggestions to make this easier to read and translate. Looking great though!

2020-10-27 13:46 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +If you want to get everything working out of the box or if you are looking for a very specific case implementation, [Vonage AI](ai.vonage.com) offers turn-key solutions made by industry experts.
```suggestion
If you want to get everything working out of the box or if you are looking for a very specific use case implementation, [Vonage AI](ai.vonage.com) offers turn-key solutions made by industry experts.
```

2020-10-27 13:46 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +*After the call is completed*, it is likely you may want to keep the keynotes, as well as be able to search through the recordings. In order to do that, the Voice API allows you to record every call
```suggestion
*After the call is completed*, it is likely you may want to keep the keynotes, as well as be able to search through the recordings. In order to do that, the Voice API enables you to record every call or part of the call so that you can store and analyze it. Learn how to do that with our [Transcribe a Recorded Call with Amazon Transcribe](/use-cases/trancribe-amazon-api) complete tutorial.
```

2020-10-27 13:46 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +* [WebSockets](/voice/voice-api/guides/websockets) allow you to connect phone calls to any AI bot engine of your choice. Clone our [reference application](https://github.com/Nexmo/lex-connector) to q
```suggestion
* [WebSockets](/voice/voice-api/guides/websockets) allow you to connect phone calls to any AI bot engine of your choice. Clone our [reference application](https://github.com/Nexmo/lex-connector) to quickly start with [Amazon Lex](https://aws.amazon.com/lex/) integration, which applies natural language understanding (NLU) to recognize the intent of the text, enabling you to build applications with highly engaging user experiences and lifelike conversational interactions. 
```

2020-10-27 13:46 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/cci.md
> +With WebSockets, you can also embed any kind of *real-time analytics* into your contact center. With an NCCO [`connect`](/voice/voice-api/ncco-reference#connect) action, you can attach WebSocket one-
```suggestion
With WebSockets, you can also embed any kind of *real-time analytics* into your contact center. With an NCCO [`connect`](/voice/voice-api/ncco-reference#connect) action, you can attach a WebSocket one-way (or two-way, depending on the case) stream to any inbound or outbound call and then pass the media to an analytics engine, such as [Amazon Transcribe](https://aws.amazon.com/transcribe/). You can perform a deeper analysis with [Amazon Comprehend](https://aws.amazon.com/comprehend/) to provide the agent with useful insights and real-time hints during the call.
```

2020-10-28 09:11 UTC, marklewin approved these changes
LGTM @vshisterov !

2020-10-28 09:11 UTC, merged