Rebrand concept docs and guides
Nexmo/nexmo-developer pull request #3315
Opened 2020-10-28 15:19 UTC by marklewin

## Description

Change Nexmo -> Vonage in the guides and concept docs

[DEVX-4717](https://nexmoinc.atlassian.net/browse/DEVX-4717)

2020-10-28 15:56 UTC, tbedford requested changes

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/client-sdk/setup/create-your-application.md
> +If you wish to get started and experience using the SDK without any implementation of your backend, this tutorial will show you how to do so, using the [Nexmo CLI](https://github.com/Vonage/nexmo-cli
I get a 404 for https://github.com/Vonage/nexmo-cli

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/concepts/guides/glossary.md
> +Further information can be found in the [CLI repository](https://github.com/Vonage/nexmo-cli).
I get a 4040 for https://github.com/Vonage/nexmo-cli

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +Currently, you can use the beta version of the [Nexmo CLI](https://github.com/Vonage/nexmo-cli/tree/beta) to create a JWT [including the appropriate claims](https://github.com/Vonage/nexmo-cli/tree/b
404 for https://github.com/Vonage/nexmo-cli/tree/beta

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +The beta version of the [Vonage Node](https://github.com/Vonage/nexmo-node/tree/beta#jwt) library can also create a JWT [including the appropriate claims](https://github.com/Vonage/nexmo-node/tree/be
404 for https://github.com/Vonage/nexmo-cli/tree/beta

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +## Vonage Client Libraries
Vonage Server SDKs

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +The beta version of the [Vonage Node](https://github.com/Vonage/nexmo-node/tree/beta#jwt) library can also create a JWT [including the appropriate claims](https://github.com/Vonage/nexmo-node/tree/be
Library -> Server SDK

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +Vonage.generateJwt(PRIVATE_KEY, {
Has the class name definitely changed?

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +The current version of the [Vonage PHP](https://github.com/Vonage/nexmo-php) library can also create a JWT including the appropriate claims when using the Keypair authentication.
Library -> Server SDK

2020-10-28 15:56 UTC, tbedford commented on _documentation/en/conversation/guides/jwt-acl.md
> +The current version of the [Vonage PHP](https://github.com/Vonage/nexmo-php) library can also create a JWT including the appropriate claims when using the Keypair authentication.
https://github.com/Vonage/nexmo-php redirects to https://github.com/Vonage/vonage-php-sdk-core

2020-10-28 16:44 UTC, marklewin commented on _documentation/en/conversation/guides/jwt-acl.md
> +Vonage.generateJwt(PRIVATE_KEY, {
No ... good spot

2020-10-29 09:31 UTC, marklewin commented
Adding DO NOT MERGE because I want to check that this PR also addresses the issues raised in [DEVX-3912](https://nexmoinc.atlassian.net/browse/DEVX-3912)

2020-10-29 10:55 UTC, marklewin commented
Will deal with DEVX-3912 changes in a new branch. Marking as ready for review/merge.

2020-10-29 11:21 UTC, tbedford requested changes

2020-10-29 11:21 UTC, tbedford commented on _documentation/en/concepts/guides/authentication.md
> +Further information on the Nexmo CLI can be found in its [repository on GitHub](https://github.com/Vonage/nexmo-cli).
404 for https://github.com/Vonage/nexmo-cli

2020-10-29 11:52 UTC, tbedford approved these changes

2020-10-29 11:52 UTC, merged