Added a blurb to all relevant pages where USSC deprecation needs to be displayed.
Nexmo/nexmo-developer pull request #3344
Opened 2020-11-09 10:17 UTC by GregHolmes

## Description

I have updated all of the relevant pages where US Short Code is featured. These pages now have a blurb at the top announcing the deprecation of this service along with where the users can go from here. The blurb was decided by the team heading this deprecation work and is universal throughout multiple platforms that it will be displayed.

I need to get Lorenzo to approve of these changes, and a date to be given for it to be merged. But would like you to cast your eyes over this to see if you can see any problems or if there are any pages that you know of, that I may have missed out?

Thank you!

2020-11-09 12:00 UTC, marklewin approved these changes
Very minor grammatical changes x 2, but otherwise LGTM!

2020-11-09 12:00 UTC, marklewin commented on _api/sms/us-short-codes/alerts/sending.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _api/sms/us-short-codes/alerts/subscription.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/concepts/guides/glossary.md
> +10 digit long code (10DLC) is the new standard in Application 2 Person (A2P) text messaging. This standard allows businesses to have a higher volume throughput and improves security standards for mes
```suggestion
10 digit long code (10DLC) is the new standard in Application to Person (A2P) text messaging. This standard allows businesses to have a higher volume throughput and improves security standards for messaging.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/concepts/guides/glossary.md
> +**Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefo
```suggestion
**Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/dispatch/code-snippets/send-an-mms-with-failover.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/messages/code-snippets/mms/send-mms.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/messaging/us-short-codes/guides/2fa.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/messaging/us-short-codes/guides/alerts.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/messaging/us-short-codes/guides/campaign-subscription-management.md
> +>**Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, theref
```suggestion
>**Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/messaging/us-short-codes/overview.md
> +>**Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, theref
```suggestion
>**Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/numbers/guides/enable-2fa.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:00 UTC, marklewin commented on _documentation/en/numbers/guides/event-alerts.md
> +> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, there
```suggestion
> **Effective immediately, Vonage will no longer accept new programs for Shared Short Codes for A2P messaging.** T-Mobile and AT&T’s new code of conduct prohibits the use of shared originators, therefore, existing Shared Short Code traffic must be migrated by March 1, 2021. To help you with this transition, please use the Vonage [guide to alternatives](https://help.nexmo.com/hc/en-us/articles/360050905592).  Please contact us to migrate to a new solution.
```

2020-11-09 12:01 UTC, marklewin requested changes
Sorry, meant to mark as 'request changes'

2020-11-09 14:35 UTC, marklewin approved these changes
LGTM!

2020-11-13 15:51 UTC, GregHolmes commented
Hey @marklewin , is there any chance this could be deployed whenever you have time and an active slot to deploy please?

2020-11-13 16:33 UTC, merged