devx-4905
Nexmo/nexmo-developer pull request #3392
Opened 2020-11-20 15:02 UTC by tbedford

## Description

Adds some words on `connection_timeout` and `socket_timeout`.

2020-11-20 16:30 UTC, tbedford commented
@vshisterov @JamieChapman8462 - your feedback most welcome! Thank you!

2020-11-20 16:59 UTC, JamieChapman8462 approved these changes

2020-11-23 09:36 UTC, marklewin requested changes
I wonder if we should say what these parameters are expecting, otherwise someone might think they are just booleans? Something like:

"If Vonage can't connect to the webhook URL, a timeout will occur after the specified time in (seconds?). Vonage then makes one additional attempt to connect to the webhook endpoint."

And is it really a timeout if "Vonage then makes one additional attempt to connect to the webhook endpoint."?

2020-11-23 13:17 UTC, tbedford commented
@marklewin - it was a bit rushed. Hopefully better now? Let me know. Thanks.

2020-11-23 13:59 UTC, marklewin approved these changes
Great!

2020-11-23 13:59 UTC, merged