DEVX-4689 Remove more Nexmo references
Nexmo/nexmo-developer pull request #3401
Opened 2020-11-27 08:49 UTC by bencgreenberg

## Description

There are still lots of references to Nexmo in the docs. Some of them reflect the names of our repositories and some reflect the term "Nexmo CLI", but others can be changed. This is a big sweep through those.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2020-11-27 09:51 UTC, tbedford requested changes

2020-11-27 09:51 UTC, tbedford commented on .github/CONTRIBUTING.md
> +We welcome everybody contributing to Vonage API Developer. These guidelines outline how to contribute reports, bug fixes, features, suggestions and content.
You have modified a `.github` file here.

2020-11-27 09:51 UTC, tbedford commented on _documentation/en/account/guides/dashboard-management.md
> +If you are still having issues, please contact <support@vonage.com>.
Is this actually the support address?

2020-11-27 09:51 UTC, tbedford commented on _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
> +        // "Not a Vonage push!!"
At the moment Client SDK code uses Nexmo throughout. May cause confusion to change this one?

2020-11-27 09:51 UTC, tbedford commented on _tutorials/en/client-sdk/android-shared/create-users-alice-and-bob.md
> +Execute the following commands in the terminal to create two users, `Alice` and `Bob` who will log in to the Vonage Client and communicate.
I think this perhaps should be `NexmoClient`.

2020-11-27 09:51 UTC, tbedford commented on _tutorials/en/client-sdk/in-app-messaging/create-users/objective_c.md
> +Execute the following commands to create two users, `Alice` and `Bob` who will log in to the Vonage Client and participate in the chat (Conversation).
Again `NexmoClient`?

2020-11-27 09:51 UTC, tbedford commented on _documentation/en/account/guides/dashboard-management.md
> +* [Create and configure a Vonage account](#create-and-configure-a-vonage-account)
Can we make sure breaking this doesn't break the link?

2020-11-27 09:53 UTC, bencgreenberg commented on _documentation/en/account/guides/dashboard-management.md
> +* [Create and configure a Vonage account](#create-and-configure-a-vonage-account)
The link was broken already, since the title was changed further down previously but the link was not updated. This fixes it.

2020-12-01 07:42 UTC, bencgreenberg commented on _documentation/en/account/guides/dashboard-management.md
> +If you are still having issues, please contact <support@vonage.com>.
Yes, I believe so based on updates on Slack. If you search through Slack you'll see that's the address being used.

2020-12-01 07:43 UTC, bencgreenberg commented on _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
> +        // "Not a Vonage push!!"
That's true. I'll revert these.

2020-12-01 08:02 UTC, bencgreenberg commented
@tbedford thanks for the review. I reverted the changes that didn't make sense as you pointed out. I believe it's ready for another look over when you have a moment.

2020-12-01 09:57 UTC, tbedford approved these changes

2020-12-01 09:57 UTC, merged