DEVX-2258
Nexmo/nexmo-developer pull request #3405
Opened 2020-12-01 10:03 UTC by bencgreenberg

## Description

We check our content for spelling, but we do not yet check our content for offensive qualities or ableist or gendered language, etc. This PR incorporates [alex](https://github.com/get-alex/alex) into ADP and fixes all the current issues in the docs.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2020-12-01 11:13 UTC, mheap commented on _documentation/en/client-sdk/in-app-messaging/guides/inviting-members.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
I'm not sure `light` is the correct phrasing here

2020-12-01 11:14 UTC, mheap commented on _documentation/en/concepts/guides/webhooks.md
> +**Start small** - Publish the smallest possible script that you can think of to respond when the webhook is received and perhaps print some debug information. This makes sure that the URL is what you
Small could also be complex. Maybe `minimal`?

2020-12-01 11:16 UTC, mheap commented on _documentation/en/concepts/guides/openapi.md
> +One tool that many of our developers find useful is [Prism](https://stoplight.io/open-source/prism). It's an open source JavaScript tool that accepts an OpenAPI spec and then imitates the API behavio
```suggestion
One tool that many of our developers find useful is [Prism](https://stoplight.io/open-source/prism). It's an open source JavaScript tool that accepts an OpenAPI spec and then imitates the API behavior it describes. It's an ideal way to work with a local API, avoids using up account credit when you're testing something, and also provides a way to test error responses locally.
```

2020-12-01 11:17 UTC, mheap commented on _documentation/en/tools/prism.md
> +Our APIs can return error responses in some situations, and it can be difficult (or plainly annoying) to recreate those error situations on the live platform. Using Prism gives an opportunity to test
```suggestion
Our APIs can return error responses in some situations, and it can be difficult to recreate those error situations on the live platform. Using Prism gives an opportunity to test applications against all the possible responses.
```

2020-12-01 11:18 UTC, mheap commented on _documentation/en/voice/sip/concepts/programmable-sip.md
> +IP addresses of your devices and endpoints can be configured to reach your Vonage application. Vonage will only accept calls from the IP address list that is configured for your domain. This method w
```suggestion
IP addresses of your devices and endpoints can be configured to reach your Vonage application. Vonage will only accept calls from the IP address list that is configured for your domain. This method will enable you to add your endpoints’ and devices’ IP Addresses per your application to your allow list.
```

2020-12-01 11:19 UTC, mheap commented on _partials/stitch/guides/enable-screenshare/javascript.md
> +We'll need to install the extension on Chrome. There are a few ways to do that, the first being to publish it in the Chrome App store. But that's a lengthy process so we're opting for enabling develo
```suggestion
We'll need to install the extension on Chrome. There are a few ways to do that, the first being to publish it in the Chrome App store. But that's a lengthy process so we're opting for enabling developer extensions and installing it from there. You'll need to open [chrome://extensions/](chrome://extensions/) an toggle `Developer Mode` in the right hand corner. A few more buttons will appear in the UI and we'll use `LOAD UNPACKED` and point that to the folder we have now created for our extension, `chrome-extension`. That automatically installs and enables the extension we now created, and lists the extension id. It looks something like `aaaabbbbccccddddeeeeffffgggghhhh` and we'll have to make a note of it, we'll be using it later.
```

2020-12-01 11:20 UTC, mheap commented on _tutorials/en/client-sdk/app-to-app/call-code.md
> +1. A small UI that allows you to enter a username and then click the `Call` button to make the the in-app call to the specified user (Bob).
```suggestion
1. A UI that allows you to enter a username and then click the `Call` button to make the the in-app call to the specified user (Bob).
```

2020-12-01 11:20 UTC, mheap commented on _tutorials/en/client-sdk/app-to-app/create-project/objective_c.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:20 UTC, mheap commented on _tutorials/en/client-sdk/app-to-app/create-project/swift.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:20 UTC, mheap commented on _tutorials/en/client-sdk/app-to-app/receive-code.md
> +1. A small UI that allows you to see if there is an inbound call and click `Answer` to answer it.
```suggestion
1. A UI that allows you to see if there is an inbound call and click `Answer` to answer it.
```

2020-12-01 11:21 UTC, mheap commented on _tutorials/en/client-sdk/app-to-phone/js-code.md
> +1. A small UI that allows you to enter a phone number and then click the `Call` button to make the voice call.
```suggestion
1. A UI that allows you to enter a phone number and then click the `Call` button to make the voice call.
```

2020-12-01 11:21 UTC, mheap commented on _tutorials/en/client-sdk/app-to-phone/project/objective_c.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:21 UTC, mheap commented on _tutorials/en/client-sdk/app-to-phone/project/swift.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:21 UTC, mheap commented on _tutorials/en/client-sdk/in-app-messaging/create-project/objective_c.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:22 UTC, mheap commented on _tutorials/en/client-sdk/in-app-messaging/create-project/swift.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:22 UTC, mheap commented on _tutorials/en/client-sdk/phone-to-app/project/objective_c.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:22 UTC, mheap commented on _tutorials/en/client-sdk/phone-to-app/project/swift.md
> +**Before continuing, please close the new project you've now created.**
```suggestion
**Before continuing, please close the new project you created.**
```

2020-12-01 11:42 UTC, tbedford requested changes
Wow, tech writers will soon be redundant!

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/client-sdk/in-app-messaging/guides/inviting-members.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
This should just be "create a conversation".

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/client-sdk/in-app-messaging/guides/seen-receipt.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
This should just be "create a conversation".

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/client-sdk/in-app-messaging/guides/send-receive-image.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
This should just be "create a conversation".

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/client-sdk/in-app-messaging/guides/send-receive-text.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
This should just be "create a conversation".

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/client-sdk/in-app-messaging/guides/typing-indicators.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
This should just be "create a conversation".

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/concepts/guides/openapi.md
> +One tool that many of our developers find useful is [Prism](https://stoplight.io/open-source/prism). It's an open source JavaScript tool that accepts an OpenAPI spec and then imitates the API behavio
"and also gives an coherent way to test error responses" -> "and provides a way to test error responses"

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/tools/prism.md
> +Our APIs can return error responses in some situations, and it can be difficult (or plainly annoying) to recreate those error situations on the live platform. Using Prism gives an opportunity to test
"it can be difficult (or plainly annoying) to recreate those error situations" -> "it can be difficult to recreate those error situations"

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/voice/sip/concepts/programmable-sip.md
> +IP addresses of your devices and endpoints can be configured to reach your Vonage application. Vonage will only accept calls from the IP address list that is configured for your domain. This method w
"This method will enable you to ad your" -> This method enables you to add your

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/voice/voice-api/guides/cci.md
> +* [Text-to-Speech](/voice/voice-api/guides/text-to-speech) and [Speech Recognition](/voice/voice-api/guides/asr) for advanced IVR or basic voice bots. Follow this [tutorial](/use-cases/asr-use-case-v
"or basic voice bots" -> or voice bots.

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/voice/voice-api/guides/cci.md
> +Vonage deals with the complexity of connecting the call, so all you need is to provision a Vonage virtual number, assign it to your app, and implement HTTP request handlers ([webhooks](/voice/voice-a
"Building an IVR is this straightforward." - delete.

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/voice/voice-api/guides/cci.md
> +If you want to enhance your IVR with natural language understanding (NLU), you may connect it to an AI service, such as [Amazon Lex](https://aws.amazon.com/lex/). Lex accepts both text and media (aud
Errant space between "Then you" and "need".

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/voice/voice-api/guides/text-to-speech.md
> +The following example NCCO shows a light use case:
"The following example NCCO shows a light use case:" -> "The following NCCO demonstrates an example use case:"

2020-12-01 11:42 UTC, tbedford commented on _documentation/en/voice/voice-api/guides/websockets.md
> +* Automating outbound calls with bots to perform tasks like making a restaurant booking or more complex ones, such as requesting information from field experts.
"perform tasks like making a" -> perform tasks such as

2020-12-01 11:42 UTC, tbedford commented on _partials/stitch/guides/enable-audio/javascript.md
> +In this guide we'll cover adding audio events to the Conversation we have created in the [small conversation with events](/client-sdk/in-app-messaging/guides/utilizing-events/javascript) guide. We'll
"small conversation with events" -> conversation with events

2020-12-01 11:42 UTC, tbedford commented on _partials/stitch/guides/enable-screenshare/javascript.md
> +In this getting started guide we'll cover updating media streams to add screen sharing to the Conversation we created in the [small conversation with video](/client-sdk/in-app-video/guides/enable-vid
"small conversation with video" -> conversation with video

2020-12-01 11:42 UTC, tbedford commented on _partials/stitch/guides/enable-video/javascript.md
> +In this getting started guide we'll cover adding video events to the Conversation we created in the [small conversation with audio](/client-sdk/in-app-voice/guides/enable-audio/javascript) getting st
"small conversation with audio" -> conversation with audio

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/app-to-app/call-code.md
> +1. A small UI that allows you to enter a username and then click the `Call` button to make the the in-app call to the specified user (Bob).
"A small UI" -> A UI

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/app-to-app/receive-code.md
> +1. A small UI that allows you to see if there is an inbound call and click `Answer` to answer it.
"A small UI" -> A UI

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/app-to-phone/js-code.md
> +1. A small UI that allows you to enter a phone number and then click the `Call` button to make the voice call.
"A small UI" -> A UI

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/phone-to-app/call/java.md
> +At the top of the `MainActivity` class, right below the view declarations, add a `call` property to hold a reference to any call in progress and `incomingCall` property to hold information about curr
"right below the view declarations" -> "below the view declarations"

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/phone-to-app/call/kotlin.md
> +At the top of the `MainActivity` class, right below the view declarations, add a `call` property to hold a reference to any call in progress and `incomingCall` property to hold information about curr
"right below the view declarations" -> "below the view declarations"

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/phone-to-app/call/objective_c.md
> +At the top of the `ViewController` class, right below the `client` declaration, add a `NXMCall` property to hold a reference to any call in progress.
"right below the" -> "below the"

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/client-sdk/phone-to-app/call/swift.md
> +At the top of the `ViewController` class, right below the `client` declaration, add a `NXMCall` property to hold a reference to any call in progress.
"right below the" -> "below the"

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/sms-api/add-sms-controller-receive.md
> +Finally we'll need to add a route to receive the webhook from Vonage, parse out the SMS data structure, and print some stuff to our console:
"Finally we'll need to add a route to receive the webhook from Vonage, parse out the SMS data structure, and print some stuff to our console" -> "Now add a route to receive the webhook from Vonage, parse the SMS structure, and print data to the console:" 

(Flagging @niati as the content specialist for SMS - this tutorial probably needs a review to make sure it's compliant with our writing style guide and raise another PR to fix where appropriate once this one has been merged).

2020-12-01 11:42 UTC, tbedford commented on _tutorials/en/verify/2fa-ruby-add-number-to-model.md
> +Devise enables you to edit a user right out of the box. By default these views are hidden, so we need to get a copy of them to make changes to. Devise makes this pretty straightforward through a Rail
"Devise makes this pretty straightforward through a Rails generator, which you would run using `rails generate:devise:views:templates`." -> "Devise provides a Rails generator for creating a copy of the templates you need to edit. You run the generator using the command `rails generate:devise:views:templates`". @marklewin can you confirm this is correct or suggest alternative please? Thanks

2020-12-01 11:42 UTC, tbedford commented on .github/workflows/ci.yml
> +    - name: Check prose issues
Just flagging up that a `.github` file was modified but I think it's intentional in this case.

2020-12-01 12:11 UTC, bencgreenberg commented on _documentation/en/client-sdk/in-app-messaging/guides/inviting-members.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
```suggestion
Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation).
```

2020-12-01 12:11 UTC, bencgreenberg commented on _documentation/en/client-sdk/in-app-messaging/guides/seen-receipt.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
```suggestion
Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation).
```

2020-12-01 12:11 UTC, bencgreenberg commented on _documentation/en/client-sdk/in-app-messaging/guides/send-receive-image.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
```suggestion
Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation).
```

2020-12-01 12:12 UTC, bencgreenberg commented on _documentation/en/client-sdk/in-app-messaging/guides/send-receive-text.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
```suggestion
Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation).
```

2020-12-01 12:12 UTC, bencgreenberg commented on _documentation/en/client-sdk/in-app-messaging/guides/typing-indicators.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a light conversation](/client-sdk/in-app-messaging/guides/simple-convers
```suggestion
Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation).
```

2020-12-01 12:14 UTC, bencgreenberg commented on _documentation/en/concepts/guides/webhooks.md
> +**Start small** - Publish the smallest possible script that you can think of to respond when the webhook is received and perhaps print some debug information. This makes sure that the URL is what you
```suggestion
**Start small** - Publish the most minimal script that you can think of to respond when the webhook is received and perhaps print some debug information. This makes sure that the URL is what you think it is, and that you can see the output or logs of the application.
```

2020-12-01 12:14 UTC, bencgreenberg commented on _documentation/en/concepts/guides/webhooks.md
> +**Start small** - Publish the smallest possible script that you can think of to respond when the webhook is received and perhaps print some debug information. This makes sure that the URL is what you
@mheap - I left the header alone as "Start small" is a common expression but then defined it as minimal in the description per your suggestion.

2020-12-01 12:15 UTC, bencgreenberg commented on _documentation/en/tools/prism.md
> +Our APIs can return error responses in some situations, and it can be difficult (or plainly annoying) to recreate those error situations on the live platform. Using Prism gives an opportunity to test
```suggestion
Our APIs can return error responses in some situations, and it can be difficult to recreate those error situations on the live platform. Using Prism gives an opportunity to test applications against all the possible responses.
```

2020-12-01 12:17 UTC, bencgreenberg commented on _tutorials/en/client-sdk/phone-to-app/call/objective_c.md
> +At the top of the `ViewController` class, right below the `client` declaration, add a `NXMCall` property to hold a reference to any call in progress.
```suggestion
At the top of the `ViewController` class, below the `client` declaration, add a `NXMCall` property to hold a reference to any call in progress.
```

2020-12-01 12:17 UTC, bencgreenberg commented on _tutorials/en/client-sdk/phone-to-app/call/swift.md
> +At the top of the `ViewController` class, right below the `client` declaration, add a `NXMCall` property to hold a reference to any call in progress.
```suggestion
At the top of the `ViewController` class, below the `client` declaration, add a `NXMCall` property to hold a reference to any call in progress.
```

2020-12-01 12:18 UTC, bencgreenberg commented on _tutorials/en/sms-api/add-sms-controller-receive.md
> +Finally we'll need to add a route to receive the webhook from Vonage, parse out the SMS data structure, and print some stuff to our console:
Sounds good. I'll "resolve" this conversation for now for this PR's sake.

2020-12-01 12:19 UTC, bencgreenberg commented on _tutorials/en/verify/2fa-ruby-add-number-to-model.md
> +Devise enables you to edit a user right out of the box. By default these views are hidden, so we need to get a copy of them to make changes to. Devise makes this pretty straightforward through a Rail
```suggestion
Devise provides a Rails generator for creating a copy of the templates you need to edit. You run the generator using the command `rails generate:devise:views:templates`.
```

@marklewin please confirm and if so go ahead and commit this suggestion per @tbedford's comment

2020-12-01 12:20 UTC, bencgreenberg commented on .github/workflows/ci.yml
> +    - name: Check prose issues
Yes, this adds it to the CI similar to the spell checking check

2020-12-01 12:49 UTC, marklewin requested changes
A few minor editorial suggestions, but otherwise looks good

2020-12-01 12:49 UTC, marklewin commented on _documentation/en/messages/overview.md
> +The following diagram illustrates how the Vonage Messages API enables you to send messages over multiple channels with minimal work:
@bencgreenberg I think I'd prefer something like "...via multiple channels from a single endpoint". That way we can state the benefit instead of just saying words to the effect of "it's easy". What do you think?

2020-12-01 12:49 UTC, marklewin commented on _documentation/en/tools/prism.md
> +Working with APIs is great but sometimes you don't need to work with the real API to get development work done. One tool that you may find useful to include in your development workflow is [Prism](ht
```suggestion
Working with APIs is great but sometimes you don't need to work with the real API to get development work done. One tool that you may find useful to include in your development workflow is [Prism](https://stoplight.io/open-source/prism/) from [Stoplight](https://stoplight.io/). Prism is a mock server that imitates our live APIs. You can run it locally to test your API calls during development, without incurring any usage costs.
```

2020-12-01 12:49 UTC, marklewin commented on _documentation/en/voice/sip/concepts/programmable-sip.md
> +IP addresses of your devices and endpoints can be configured to reach your Vonage application. Vonage will only accept calls from the IP address list that is configured for your domain. This method w
```suggestion
You can configure an Access Control List for your domain so that your Vonage application will only accept calls from specific endpoints and devices. You do this by adding their IP addresses to an allow list.
```

2020-12-01 12:49 UTC, marklewin commented on _partials/stitch/guides/enable-screenshare/javascript.md
> +We'll need to install the extension on Chrome. There are a few ways to do that, the first being to publish it in the Chrome App store. But that's a lengthy process so we're opting for enabling develo
**an** toggle developer mode -> **and** toggle developer mode

2020-12-01 12:49 UTC, marklewin commented on _tutorials/en/join-github.md
> +If you recently signed up, please ensure that you [verified your email address](https://help.github.com/en/github/getting-started-with-github/verifying-your-email-address) and are logged in.
"If you have recently signed up", or "if you signed up recently"

2020-12-01 12:54 UTC, bencgreenberg commented on _documentation/en/messages/overview.md
> +The following diagram illustrates how the Vonage Messages API enables you to send messages over multiple channels with minimal work:
I agree! If you'd like to modify it as a suggestion, I'll gladly commit it ❤️

2020-12-01 12:55 UTC, bencgreenberg commented on _partials/stitch/guides/enable-screenshare/javascript.md
> +We'll need to install the extension on Chrome. There are a few ways to do that, the first being to publish it in the Chrome App store. But that's a lengthy process so we're opting for enabling develo
```suggestion
We'll need to install the extension on Chrome. There are a few ways to do that, the first being to publish it in the Chrome App store. But that's a lengthy process so we're opting for enabling developer extensions and installing it from there. You'll need to open [chrome://extensions/](chrome://extensions/) and toggle `Developer Mode` in the right hand corner. A few more buttons will appear in the UI and we'll use `LOAD UNPACKED` and point that to the folder we have now created for our extension, `chrome-extension`. That automatically installs and enables the extension we now created, and lists the extension id. It looks something like `aaaabbbbccccddddeeeeffffgggghhhh` and we'll have to make a note of it, we'll be using it later.
```

2020-12-01 12:56 UTC, bencgreenberg commented on _partials/stitch/guides/enable-video/javascript.md
> +In this getting started guide we'll cover adding video events to the Conversation we created in the [small conversation with audio](/client-sdk/in-app-voice/guides/enable-audio/javascript) getting st
```suggestion
In this getting started guide we'll cover adding video events to the Conversation we created in the [conversation with audio](/client-sdk/in-app-voice/guides/enable-audio/javascript) getting started guide. We'll deal with video and media stream events, the ones that come via the conversation, and the ones we send to the conversation.
```

2020-12-01 12:57 UTC, bencgreenberg commented on _partials/stitch/guides/enable-video/javascript.md
> +In this getting started guide we'll cover adding video events to the Conversation we created in the [small conversation with audio](/client-sdk/in-app-voice/guides/enable-audio/javascript) getting st
```suggestion
In this getting started guide we'll cover adding video events to the Conversation we created in the [conversation with audio](/client-sdk/in-app-voice/guides/enable-audio/javascript) getting started guide. We'll deal with video and media stream events, the ones that come via the conversation, and the ones we send to the conversation.
```

2020-12-01 12:57 UTC, bencgreenberg commented on _tutorials/en/client-sdk/phone-to-app/call/java.md
> +At the top of the `MainActivity` class, right below the view declarations, add a `call` property to hold a reference to any call in progress and `incomingCall` property to hold information about curr
```suggestion
At the top of the `MainActivity` class, below the view declarations, add a `call` property to hold a reference to any call in progress and `incomingCall` property to hold information about the currently incoming call.
```

2020-12-01 12:58 UTC, bencgreenberg commented on _tutorials/en/client-sdk/phone-to-app/call/kotlin.md
> +At the top of the `MainActivity` class, right below the view declarations, add a `call` property to hold a reference to any call in progress and `incomingCall` property to hold information about curr
```suggestion
At the top of the `MainActivity` class, below the view declarations, add a `call` property to hold a reference to any call in progress and `incomingCall` property to hold information about the currently incoming call.
```

2020-12-01 13:52 UTC, bencgreenberg commented on _tutorials/en/join-github.md
> +If you recently signed up, please ensure that you [verified your email address](https://help.github.com/en/github/getting-started-with-github/verifying-your-email-address) and are logged in.
```suggestion
If you have recently signed up, please ensure that you [verified your email address](https://help.github.com/en/github/getting-started-with-github/verifying-your-email-address) and are logged in.
```

2020-12-01 14:37 UTC, tbedford commented
@bencgreenberg - it looks like you missed a number of my comments - probably one of those "click to expand..." things.

2020-12-01 14:38 UTC, tbedford requested changes
Still quite a few comments not addressed.

2020-12-01 14:47 UTC, marklewin requested changes

2020-12-01 14:47 UTC, marklewin commented on _documentation/en/messages/overview.md
> +The following diagram illustrates how the Vonage Messages API enables you to send messages over multiple channels with minimal work:
```suggestion
The following diagram illustrates how the Vonage Messages API enables you to send messages via multiple channels from a single endpoint:
```

2020-12-01 14:47 UTC, marklewin commented on _documentation/en/messages/overview.md
> +The following diagram illustrates how the Vonage Messages API enables you to send messages over multiple channels with minimal work:
@bencgreenberg Done! 😄

2020-12-01 14:54 UTC, bencgreenberg commented
> @bencgreenberg - it looks like you missed a number of my comments - probably one of those "click to expand..." things.

You are correct! They were hidden by the UI. I'll get to them tonight and tomorrow morning re-request a review again.

2020-12-01 15:30 UTC, bencgreenberg commented on _documentation/en/concepts/guides/openapi.md
> +One tool that many of our developers find useful is [Prism](https://stoplight.io/open-source/prism). It's an open source JavaScript tool that accepts an OpenAPI spec and then imitates the API behavio
```suggestion
One tool that many of our developers find useful is [Prism](https://stoplight.io/open-source/prism). It's an open source JavaScript tool that accepts an OpenAPI spec and then imitates the API behavior it describes. It's an ideal way to work with a local API, avoids using up account credit when you're testing something, and also gives a way to test error responses.
```

2020-12-01 15:40 UTC, bencgreenberg commented
@tbedford I think I addressed all your comments and is ready for another look.

2020-12-02 11:58 UTC, tbedford approved these changes

2020-12-02 12:47 UTC, merged