Facebook messenger privacy changes for euro
Nexmo/nexmo-developer pull request #3426
Opened 2020-12-04 19:18 UTC by slorello89

## Description

Facebook is making some changes effective December 16th that will effect the Messenger channel of the Message API - this PR makes sure those changes are accounted for in the docs.

2020-12-07 10:23 UTC, marklewin requested changes

2020-12-07 10:23 UTC, marklewin commented on _documentation/en/messages/code-snippets/messenger/send-audio.md
> +> NOTE: This feature is generally available, however due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected
I'm just wondering whether we should be using the words "generally available" to apply to an API that's still marked as being in beta? Perhaps we could just say:

"Due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected)"

2020-12-07 10:23 UTC, marklewin commented on _documentation/en/messages/code-snippets/messenger/send-file.md
> +> NOTE: This feature is generally available, however due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected
I'm just wondering whether we should be using the words "generally available" to apply to an API that's still marked as being in beta? Perhaps we could just say:

"Due to privacy regulations this feature may be limited in Europe"

2020-12-07 10:23 UTC, marklewin commented on _documentation/en/messages/code-snippets/messenger/send-template.md
> +> NOTE: This feature is generally available, however due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected
I'm just wondering whether we should be using the words "generally available" to apply to an API that's still marked as being in beta? Perhaps we could just say:

"Due to privacy regulations this feature may be limited in Europe"

2020-12-07 10:23 UTC, marklewin commented on _documentation/en/messages/code-snippets/messenger/send-video.md
> +> NOTE: This feature is generally available, however due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected
I'm just wondering whether we should be using the words "generally available" to apply to an API that's still marked as being in beta? Perhaps we could just say:

"Due to privacy regulations this feature may be limited in Europe"

2020-12-07 10:23 UTC, marklewin commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
What is the significance of the dash compared to "n/a"? Perhaps we should use dash in place of n/a for the other APIs too?

2020-12-07 15:21 UTC, slorello89 commented on _documentation/en/messages/code-snippets/messenger/send-audio.md
> +> NOTE: This feature is generally available, however due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected
Would "globally" make more sense?

2020-12-07 15:22 UTC, slorello89 commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
the dash is mean to be somewhere in between a n/a and a checkmark - do you have a different idea for an emoji?

2020-12-07 17:12 UTC, marklewin commented on _documentation/en/messages/code-snippets/messenger/send-audio.md
> +> NOTE: This feature is generally available, however due to privacy regulations this feature may be [limited in Europe](https://developers.facebook.com/docs/messenger-platform/europe-updates#affected
Hey @slorello89 ... I think we can more clearly show that it's generally and globally available just by stating where it's not? Or am I missing the point here?

2020-12-07 17:13 UTC, marklewin commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
What's the difference between N/A and a dash? Are we just saying in both instances that this feature isn't available?

2020-12-07 17:15 UTC, marklewin commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
Or are we saying in the case of a dash that the feature is not available yet, but might be in future? And, if so, does the same thing apply to some/all of the "N/A's"? @niati - As content specialist, do you have any insight here?

2020-12-07 17:20 UTC, slorello89 commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
It's trying to express that it's available everywhere, except for some limitations in Europe.

2020-12-07 17:22 UTC, slorello89 commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
I'd put a checkmark and a † but the renderer doesn't seem to want them to have the same line.

2020-12-07 18:48 UTC, niati commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
I agree - the dash is a bit confusing. I would think it is the same as n/a. @marklewin  do you think Ben or Fabian have any idea how we can keep the checkmark graphic and the † on the same line?

2020-12-08 09:48 UTC, marklewin commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
@slorello89 @niati : Please see latest commit and see if you think it works for the info you are trying to convey. I removed the unused items from the legend. I'm not precious about it, so feel free to reject it if you think it makes things worse!

2020-12-08 13:08 UTC, slorello89 commented on _documentation/en/messages/overview.md
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
I think it's better. Since there's a single source of all the issues, might it be more prescient to link to the single source (e.g. the Facebook developers page linked to?)

2020-12-08 13:44 UTC, marklewin commented
For now, I think. But going forward, it might be nice to just use that
symbol for more general limitations?

On Tue, 8 Dec 2020 at 13:08, Stephen Lorello <notifications@github.com>
wrote:

> *@slorello89* commented on this pull request.
> ------------------------------
>
> In _documentation/en/messages/overview.md
> <https://github.com/Nexmo/nexmo-developer/pull/3426#discussion_r538348127>
> :
>
> > @@ -42,14 +42,14 @@ Channel | Outbound Text | Outbound Image | Outbound Audio | Outbound Video | Out
>
>  SMS | ✅ | n/a | n/a | n/a | n/a | n/a
>
>  MMS | ✅ | ✅ | n/a | n/a | n/a | n/a
>
>  Viber Service Messages | ✅ | ✅ | n/a | n/a | n/a | ✅
>
> -Facebook Messenger | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
>
> +Facebook Messenger | ✅ | ✅ | ➖ | ➖ | ➖ | ➖
>
>
> I think it's better. Since there's a single source of all the issues,
> might it be more prescient to link to the single source (e.g. the Facebook
> developers page linked to?)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexmo/nexmo-developer/pull/3426#discussion_r538348127>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEKVV43X4Q3VZPP2OTJ2O3DSTYQN3ANCNFSM4UN3E5CQ>
> .
>

2021-02-24 09:14 UTC, bencgreenberg commented
Is this PR moving forward or shall we close? @slorello89 @marklewin

2021-02-26 12:30 UTC, bencgreenberg commented
Closing due to inactivity, welcome to reopen when/if it becomes ready to act upon again.

2021-02-26 12:30 UTC, closed without merging