Check Use Cases for Spelling and Offensive Language
Nexmo/nexmo-developer pull request #3444
Opened 2020-12-10 11:04 UTC by bencgreenberg

## Description

* Adds the spell checker and the offensive language checker to use_cases in the CI
* Fixes the issues identified

2020-12-11 10:08 UTC, marklewin requested changes
Loving this Alex stuff, @bencgreenberg ! Just a couple of minor suggestions.

2020-12-11 10:08 UTC, marklewin commented on _use_cases/en/interactive-voice-response.md
> -We have methods to assist us in communicating these values clearly to the user. First: the `talkDate` method just returns a string with a date format that works well for spoken words.
I wonder why Alex disliked "clearly" here? Don't get me wrong: I think the sentence is better without it ... just interested in what it was thinking!

2020-12-11 10:08 UTC, marklewin commented on _use_cases/en/real-time-feed.md
> +After this you will then receive a real-time price on your selected stock symbol. If you want to additionally sign up on another channel you are free to do so. Also, if you want to change your stock
```suggestion
After this you will then receive a real-time price on your selected stock symbol. If you want to additionally sign up on another channel you are free to do so. Also, if you want to change your stock symbol, send in a message with the new symbol: it will be acknowledged, and the data stream will change accordingly.
```

2020-12-11 10:08 UTC, marklewin commented on _use_cases/en/real-time-feed.md
> +To test with SMS send in an SMS as you did before. You will receive a help message. Send a message back with the stock symbol of either `MSFT` or `GOOGL`. You will then periodically receive a (simula
```suggestion
To test with SMS send in an SMS as you did before. You will receive a help message. Send a message back with the stock symbol of either `MSFT` or `GOOGL`. You will then periodically receive a (simulated) price update. You currently have to exit the app to stop receiving these, but you could add the ability to switch these messages off, as demonstrated in [this tutorial](/tutorials/fbm-product-info).
```

2020-12-11 10:08 UTC, marklewin commented on _use_cases/en/validate-a-number.md
> +The [Ruby Server SDK](http://github.com/Vonage/vonage-ruby-sdk) makes it possible to access the Number Insight API. It also enables you to work with the other APIs, such as the Pricing API. This mean
```suggestion
The [Ruby Server SDK](http://github.com/Vonage/vonage-ruby-sdk) makes it straightforward to access the Number Insight API. It also enables you to work with the other APIs, such as the Pricing API. This means that as well as validating and sanitizing a phone number, you can confirm the cost of sending text messages and voice calls to it, as we demonstrate in the [calculate the cost](#calculate-the-cost) section of this tutorial.
```

2020-12-11 10:08 UTC, marklewin commented on _use_cases/en/voice-alerts.md
> +You now have a working, voice-alert system where you can broadcast out a text-to-speech or prerecorded message, log which calls are answered versus sent to voicemail, and receive confirmation of rece
```suggestion
You now have a working voice-alert system where you can broadcast a text-to-speech or prerecorded message, log which calls are answered versus sent to voicemail, and receive confirmation of receipt from users who receive the message.
```

2020-12-22 13:32 UTC, bencgreenberg commented on _use_cases/en/interactive-voice-response.md
> -We have methods to assist us in communicating these values clearly to the user. First: the `talkDate` method just returns a string with a date format that works well for spoken words.
I think it sees "clearly" as condescending.

2020-12-22 13:34 UTC, bencgreenberg commented on _use_cases/en/interactive-voice-response.md
> +This tutorial code uses a small router to handle these inbound webhooks. The router determines the requested URI path and uses it to map the caller's navigation through the phone menu - the same as U
Hrm.. I think that's a fundamental conversation in Alex itself. :) 

The only way around it for us to exclude checking for "simple" entirely, which I think defeats the point. If it's okay, I'd rather we remove the reference in this one instance, as even though it is probably "simple" to a lot of people, it's not going to be "simple" for every single reader.

2020-12-22 13:37 UTC, bencgreenberg commented
@marklewin when you have a moment went through and applied all the changes you suggested.

2020-12-22 19:15 UTC, mheap requested changes

2020-12-22 19:15 UTC, mheap commented on .spelling
> +NexmoMarketplaceApp.js
Wrap this in backticks to mark it as code rather than adding to the spelling file

2020-12-22 19:15 UTC, mheap commented on .spelling
> +Sendinblue
I believe the company name is SendInBlue with capitalisation

2020-12-22 19:15 UTC, mheap commented on .spelling
> +server.js
Wrap this in backticks to mark it as code rather than adding to the spelling file

2020-12-22 19:15 UTC, mheap commented on .spelling
> +pre-defined
No need for a hyphen here, `predefined` is a recognised word

2020-12-22 19:15 UTC, mheap commented on .spelling
> +user-123
Wrap this in backticks to mark it as code rather than adding to the spelling file

2020-12-23 06:40 UTC, bencgreenberg commented on .spelling
> +Sendinblue
According to their website, the company is spelled: "Sendinblue" https://www.sendinblue.com/

2020-12-23 10:07 UTC, merged