Devx -4577 remove starter project app to phone
Nexmo/nexmo-developer pull request #3461
Opened 2020-12-21 10:07 UTC by igorwojda

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2021-01-05 16:32 UTC, marklewin requested changes
Please see the grammar issues I have identified and replicate the suggested fixes across both tutorials.

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +> **NOTE** You can open any file by using `Go to file...` action. Press `Shift + Cmd + O` and enter file name.
```suggestion
> **NOTE** You can open any file by using the `Go to file...` action. Press `Shift + Cmd + O` and enter the file name.
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +Click `Code` button in top right corner to display layout XML code:
```suggestion
Click the `Code` button in the top right corner to display the layout XML code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +Replace file content with below code snippet:
```suggestion
Replace the file contents with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +Replace `ViewModel.java` file content with below code snippet:
```suggestion
Replace the contents of the `ViewModel.java` file with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +Replace file content with below code snippet:
```suggestion
Replace the file contents with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +To retrieve client instance inside `LoginViewModel` class. Usually, it would be provided it via injection, but for tutorial purposes you will retrieve instance directly using static method. Replace t
```suggestion
In a production application you would typically retrieve the client instance inside the `LoginViewModel` class via injection. However, in this tutorial, you will retrieve the instance directly. Replace the `client` property in the `LoginViewModel` class:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +Your user must be authenticated to be able to participate in the Conversation. Replace the `onLoginUser` method inside `LoginViewModel` class:
```suggestion
You must authenticate your user to enable them to participate in the Conversation. Replace the `onLoginUser` method inside `LoginViewModel` class:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +> **NOTE:** Inside `LoginFragment` class, explore the `loginUser` method. This method is called when one of the two `Login ...` buttons are clicked. This method calls the above `onLoginUser` method.
```suggestion
> **NOTE:** Examine the `loginUser` method of the `LoginFragment` class. This method is called when one of the two `Login ...` buttons are clicked and, in turn, invokes the `onLoginUser` method. 
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +When a successful connection is established you need to navigate user to `MainFragment`. Locate the `LoginViewModel` constructor and replace its body:
```suggestion
When a successful connection is established you need to navigate the user to the `MainFragment` class. Locate the `LoginViewModel` constructor and replace its body:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +The above code will monitor connection state and if the user is authenticated (`ConnectionStatus.CONNECTED`) it will navigate the user to the `MainFragment`, otherwise it will emit connection status
```suggestion
The above code monitors the connection state and if the user is authenticated (`ConnectionStatus.CONNECTED`) it will navigate the user to the `MainFragment`, otherwise it will emit the connection status to the UI (`LoginFragment`).
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +Replace `LoginFragment.java` file content with below code snippet:
```suggestion
Replace the contents of the `LoginFragment.java` file with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +You can either launch the app on the physical phone (with [USB Debugging enabled](https://developer.android.com/studio/debug/dev-options#enable)) or create a new [Android Virtual Device](https://deve
"When device is present" ... do you mean the physical device, virtual device or either?

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +You should see login screen with `Login Alice` button. After clicking user will login and empty main screen will open.
```suggestion
You should see the login screen with the `Login Alice` button. Click the button to log in and the empty main screen will open.
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +You perform this authentication using the `JWTs` generated in previous steps. Users must be authenticated to be able to participate in the Conversation. You will now build login screen (`LoginFragmen
```suggestion
Users must be authenticated before being able to participate in the Conversation. You authenticate your users with the `JWTs` that you generated in an earlier step. In this step, you will create a login screen (using the `LoginFragment` and `LoginViewModel` classes) to manage the authentication process.
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +Open `fragment_login.xml` file.
```suggestion
Open the `fragment_login.xml` file.
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +> **NOTE** You can open any file by using `Go to file...` action. Press `Shift + Cmd + O` and enter file name.
```suggestion
> **NOTE** You can open any file by using the `Go to file...` action. Press `Shift + Cmd + O` and enter the file name.
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +Click `Code` button in top right corner to display layout XML code:
```suggestion
Click the `Code` button in the top right corner to display layout XML code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +Replace file content with below code snippet:
```suggestion
Replace the file contents with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +Replace `LoginViewModel.kt` file content with below code snippet:
```suggestion
Replace the contents of the `LoginViewModel.kt` file with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +Replace file content with below code snippet:
```suggestion
Replace the file contents with the following code:
```

2021-01-05 16:32 UTC, marklewin commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/kotlin.md
> +To retrieve client instance inside `LoginViewModel` class. Usually, it would be provided it via injection, but for tutorial purposes you will retrieve instance directly using static method. Replace t
```suggestion
In a production application you would typically retrieve the client instance inside the `LoginViewModel` class via injection. However, in this tutorial, you will retrieve the instance directly. Replace the `client` property in the `LoginViewModel` class:
```

2021-01-05 20:41 UTC, niati approved these changes

2021-01-07 09:11 UTC, igorwojda commented on _tutorials/en/client-sdk/app-to-phone/authenticate-alice/java.md
> +You can either launch the app on the physical phone (with [USB Debugging enabled](https://developer.android.com/studio/debug/dev-options#enable)) or create a new [Android Virtual Device](https://deve
either

2021-01-08 11:10 UTC, marklewin approved these changes

2021-01-08 11:10 UTC, merged