Avaya SBCe SIP Configuration Guide PDF to Markdown
Nexmo/nexmo-developer pull request #3490
Opened 2021-01-14 12:51 UTC by bencgreenberg

## Description

This pull request converts the current configuration guide for Avaya SBCe into markdown format from PDF.

2021-01-18 10:43 UTC, marklewin requested changes

2021-01-18 10:43 UTC, marklewin commented on _documentation/en/voice/sip/configure/avaya-sbce.md
> +Use the display node-names IP command to verify that node names have been properly defined
It might be clearer to render these command names in code font? I notice that some of the later ones are (e.g. section 4.2.9)

```suggestion
Use the `display node-names IP` command to verify that node names have been properly defined
```

2021-01-18 10:43 UTC, marklewin commented on _documentation/en/voice/sip/configure/avaya-sbce.md
> +The change `ip-codec-set` command is used for assigning the proper codecs. For this setup, `ip-
There is an extra space after `ip- ` in the `ip-code-set 1` command here

2021-01-18 10:43 UTC, marklewin commented on _documentation/en/voice/sip/configure/avaya-sbce.md
> +Aura System Manager Web login screen is accessed via https://<IP Address/FQDN>. Use admin
The login URL is not rendering properly because of the angle brackets. Suggest putting the URL in code font (which is what we would normally do anyway)

2021-01-18 10:43 UTC, marklewin commented on _documentation/en/voice/sip/configure/avaya-sbce.md
> +*4.3.2.1 SIP Entity for Avaya SBCe*
These level 5 headings might be clearer if they are in bold?

2021-01-18 10:45 UTC, marklewin commented
Also Ben, I note that you've gone for the "number followed by dot" format for the main headings in PR #3491 ... we should adopt the same approach here.

2021-01-18 10:50 UTC, bencgreenberg commented
Thanks, @marklewin for the review. In this first round my effort was to convert each PDF into markdown format, with minimal editing from the original. Hence, the heading format is different here from the other one, as those PDFs were different from each other.

However, you're right, it's a good idea to make it consistent now, which is one of the benefits of bringing it into markdown n the first place.

2021-01-18 10:55 UTC, marklewin commented
> Thanks, @marklewin for the review. In this first round my effort was to convert each PDF into markdown format, with minimal editing from the original. Hence, the heading format is different here from the other one, as those PDFs were different from each other.
> 
> However, you're right, it's a good idea to make it consistent now, which is one of the benefits of bringing it into markdown n the first place.

💯

2021-01-19 08:25 UTC, bencgreenberg commented
@marklewin I believe it's ready for another look over 🙏🏻

2021-01-19 09:54 UTC, marklewin approved these changes
@bencgreenberg I fixed a couple of missing code font things and a bold header that was looking a bit weird. Otherwise looks good to go!

2021-01-19 10:27 UTC, merged