DEVX-4574: Document push structure
Nexmo/nexmo-developer pull request #3504
Opened 2021-01-20 15:31 UTC by abdulajet

## Description

An example of the push payload for reference. Added to the in-app voice guides
https://jira.vonage.com/browse/DEVX-4574

Page: /client-sdk/in-app-voice/guides/push-notification-payload

2021-01-20 16:06 UTC, pardel requested changes
Just one tiny change.

2021-01-20 16:06 UTC, pardel commented on _documentation/en/client-sdk/in-app-voice/guides/push-notification-payload.md
> +    "push_info": { // Information for the push notification
I think this needs to be aligned with "user_id"

2021-01-20 16:06 UTC, pardel commented on _documentation/en/client-sdk/in-app-voice/guides/push-notification-payload.md
> +    "invited_by": "<null>",
We should make the engineering aware of the <null> coming through here - I'm guessing it should be "system".

2021-01-20 16:11 UTC, abdulajet commented on _documentation/en/client-sdk/in-app-voice/guides/push-notification-payload.md
> +    "invited_by": "<null>",
Ill let ashley know

2021-01-27 11:58 UTC, pardel requested changes
a small change

2021-02-08 10:50 UTC, pardel approved these changes

2021-02-08 10:51 UTC, merged