Voice call flow update
Nexmo/nexmo-developer pull request #3521
Opened 2021-01-28 16:10 UTC by vshisterov

## Description

- Call Flow guide reworked to describe possible call scenarios.
- Contact Center Augmentation use-case added to show the possible implementation of mixed call flow described in the guide.

2021-01-28 16:21 UTC, bencgreenberg commented on .spelling
> +ad hoc
Can we use a simpler word here? Ad hoc won't be good for translation purposes.

2021-01-29 12:45 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* to [Vonage number](/numbers/overview) from a regular phone,
```suggestion
* to a [Vonage number](/numbers/overview) from a regular phone,
```

2021-01-29 12:45 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* to [SIP domain](/voice/sip/concepts/programmable-sip) assigned to the application from PBX or any SIP capable software/hardware,
```suggestion
* to a [SIP domain](/voice/sip/concepts/programmable-sip) assigned to the application from PBX or any SIP capable software/hardware,
```

2021-01-29 12:45 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* from a client application using [Client SDK](/client-sdk/overview).
```suggestion
* from a client application using the [Client SDK](/client-sdk/overview).
```

2021-01-29 12:46 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +**Outbound** calls are calls made from the Vonage platform to a regular phone number, SIP endpoint, client application or [WebSocket](/voice/voice-api/guides/websockets) server. Outbound calls are us
```suggestion
**Outbound** calls are calls made from the Vonage platform to a regular phone number, a SIP endpoint, client application, or [WebSocket](/voice/voice-api/guides/websockets) server. Outbound calls are usually initiated in response to a request made via the REST API to create a new call. Outbound calls may also be made from within the call flow of an existing call (either inbound or outbound) using the `connect` action within the [NCCO](/voice/voice-api/guides/ncco). This scenario is generally used for forwarding calls.
```

2021-01-29 12:47 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
>  When a call is answered, Vonage makes a call to the `answer_url` provided. For inbound calls the `answer_url` is fetched from the configuration of the application that the number is linked to. For ou
```suggestion
When a call is answered, Vonage makes an HTTP request to the `answer_url` provided. For inbound calls, the `answer_url` is fetched from the configuration of the application that the number is linked to. For outbound calls, an `answer_url` is provided in the API request made to create the call.
```

2021-01-29 12:48 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +You may choose to provide your NCCO as part of the request you send to create a call instead of providing an `answer_url`. This is done by providing an NCCO in the `ncco` key of your request.
```suggestion
You may choose to provide your NCCO as part of the request you send to create a call instead of providing an `answer_url`. This is done by providing a `ncco` action in the NCCO object of your request.
```

2021-01-29 12:50 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +During the call, Vonage is doing callback requests to the application using `event URL`, set in the application configuration or in the specific NCCO action as a parameter. There are two types of cal
```suggestion
During the call, Vonage is performing callback requests to the application at the `event_url`, set in the application configuration or in the NCCO action, if one is provided in the NCCO. There are two types of callbacks:
```

2021-01-29 12:50 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* notifications, for example, call status change;
```suggestion
* notifications, for example, a call status change;
```

2021-01-29 12:51 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* instructions request, for example, `input` or `notify` callback - for these events Vonage expects the application to provide new NCCO for processing, which allows implementing different logical cal
```suggestion
* instructions request, for example, on an `input` or `notify` callback - for these events Vonage expects the application to provide a new NCCO for processing, which allows implementing different logical call flows.
```

2021-01-29 12:51 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +Vonage platform sends corresponding event callbacks per each status. You can find more detail in the [Webhooks Reference](/voice/voice-api/webhook-reference).
```suggestion
The Vonage platform sends corresponding event callbacks per each status. You can find more detail in the [Webhooks Reference](/voice/voice-api/webhook-reference).
```

2021-01-29 12:53 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +NCCO and webhooks allow scripting the call as the set of messages and questions to the user which is applicable to [voice notifications](/use-cases/voice-alerts), [IVR](/use-cases/interactive-voice-r
```suggestion
NCCO and webhooks allow scripting the call as a series of messages and questions to the user, which is applicable to [voice notifications](/use-cases/voice-alerts), [IVR](/use-cases/interactive-voice-response), [voice assistants](/use-cases/asr-use-case-voice-bot) and other scenarios with a predefined list of possible events. With an NCCO, the application may instruct the Vonage platform to play the audio message ([text-to-speech](/voice/voice-api/guides/text-to-speech) or [prerecorded](/voice/voice-api/ncco-reference#stream)) and then expect user input either with [DTMF](/voice/voice-api/guides/dtmf) or [speech](/voice/voice-api/guides/asr). On user input, the application gets input callback from the user choice (digit or speech transcript), analyzes it and provides Vonage with new instructions (NCCO).
```

2021-01-29 12:54 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +In some scenarios, for example, [Private Voice Communication](/use-cases/private-voice-communication) use case, it’s required to connect two or more participants to establish a live conversation. Eac
```suggestion
In some scenarios, for example, a [Private Voice Communication](/use-cases/private-voice-communication) use case, it’s required to connect two or more participants to establish a live conversation. Each call, inbound or outbound, is automatically added to the new conversation behind the scenes. To connect it to another call with an NCCO, the application can either
```

2021-01-29 12:54 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* create a new outbound call with [`connect`](/voice/voice-api/ncco-reference#connect) action - it will be automatically joined to the same conversation;
```suggestion
* create a new outbound call with the [`connect`](/voice/voice-api/ncco-reference#connect) action - it will be automatically joined to the same conversation;
```

2021-01-29 12:54 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* move the call to existing (or new) named conversation with [`conversation`](/voice/voice-api/ncco-reference#conversation) action.
```suggestion
* move the call to an existing (or new) named conversation with the [`conversation`](/voice/voice-api/ncco-reference#conversation) action.
```

2021-01-29 12:55 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +During the conversation, the call is naturally no longer following a sequence of actions - it’s a live interaction between two or more members. To control the call during the conversation, for exampl
```suggestion
During the conversation, the call is no longer following a sequence of actions, it is now a live interaction between two or more members. To control the call during the conversation, for example, to mute/unmute a member, the application should use the [REST API](/voice/voice-api/api-reference).
```

2021-01-29 12:56 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +Using a sequence of `connect` actions, the application may join other members in the conversations (up to 50 total conversation participants).
```suggestion
Using a sequence of `connect` actions, the application may join other members in the conversation (up to 50 total conversation participants).
```

2021-01-29 12:57 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +Typical IVR usually has one or more options to speak to a live agent, sales or support person. Also, in some cases live conversation may end up with some scripted part, for example, customer satisfac
```suggestion
IVR usually has one or more options to speak to a live agent, sales, or support person. Also, in some cases a live conversation may end up with some scripted parts. For example, a customer satisfaction survey. The Voice API allows switching from one form of interaction to another so that the call flow may consist of three (or more in the complex cases) parts:
```

2021-01-29 13:00 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +The scenario described above is a typical example; however, the application may have any combination of scripted and live parts depending on a certain use-case. Try [Contact Center Augmentation tutor
```suggestion
The scenario described above is a typical example; however, the application may have any combination of scripted and live parts depending on a certain use-case. See the [Contact Center Augmentation tutorial](/use-cases/contact-center) to learn how to implement the described scenario step by step.
```

2021-01-29 13:58 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +You may choose to provide your NCCO as part of the request you send to create a call instead of providing an `answer_url`. This is done by providing an NCCO in the `ncco` key of your request.
Does this bring a little bit different meaning to "action" (which might be confusing)? It's the `ncco` attribute of the request body we're talking about here (which should contain NCCO actions inside).
Also, this sentence is not changed comparing to the [actual guide](https://developer.nexmo.com/voice/voice-api/guides/call-flow#overview)

2021-01-29 15:32 UTC, marklewin approved these changes

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +* the user calls the phone number,
"the phone number" or "your Vonage number"? Please capitalise first letter of bullets

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +* initial greeting is played, and the user selects an option with IVR,
```suggestion
* The initial greeting is read out, and the user chooses an option from the menu provided
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +DTMF input results will be sent to the specific URL you set in the `input` action: `/webhooks/input`. Add a webhook to process the result and add some user interaction.
```suggestion
DTMF input will be sent to the specific URL you set in the `input` action: `/webhooks/input`. Add a webhook to process the result and provide some user interaction.
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +  "from": <USER_NUMBER>,
We should be using standard variable placeholder names here - see the `/config/code_snippet_variables.yml` file

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +So you should use the `dtmf.digits` array for further analysis. To connect both user and agent of the corresponding department, you'll create an outbound call to the agent endpoint. You can use a tes
```suggestion
Retrieve the user's input from the `dtmf.digits` array to determine the options they selected. To connect both user and agent of the corresponding department, you'll create an outbound call to the agent endpoint. You can use a test phone number in this sample for simplicity, for example, your mobile number. In real life, the endpoint might be a PSTN number or [SIP endpoint](/voice/sip/concepts/programmable-sip) to connect your existing PBX or contact center. It could also be a WebRTC client if you are developing your contact center solution from scratch - the Vonage [Client SDK](/client-sdk/overview) provides everything you need to implement your own Contact Center agent application.
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +Finally, both calls (legs) should be moved to one conference room (named [conversation](/voice/voice-api/ncco-reference#conversation)). To do that, you should use `conversation` action with the same
```suggestion
Finally, both calls (legs) should be moved to one conference room (named [conversation](/voice/voice-api/ncco-reference#conversation)). To do that, use the `conversation` action with the same `name` both for the user call (the inbound leg) and the agent call (the outbound leg). To generate the conversation name, you may use any unique ID generation method (for example, a timestamp).
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +> As an option, you may use `connect` action in the NCCO to connect the user to the agent. The difference is that with `connect`, the call will be immediately completed when any of the call participa
```suggestion
> As an option, you may use `connect` action in the NCCO to connect the user to the agent. The difference is that with `connect`, the call will terminate as soon as any participant hangs up, and there is only one leg left. If that happens, it would be impossible to transfer the user to the survey after the call. If you want the user to remain connected to the call after the agent leaves, choose the `conversation` action instead, as shown in the example below.
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +      departmentNumber = <YOUR_MOBILE_NUMBER>
Please use standard variable names

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +Next, to implement the customer satisfaction survey at the end of the call, you should handle `completed` event for the agent's leg. It will arrive at the same event webhook, so you should extend the
```suggestion
Next, to implement the customer satisfaction survey at the end of the call, you should handle the `completed` event for the agent's leg. It will arrive at the same event webhook, so you should extend the event webhook with a [transfer request](/voice/voice-api/code-snippets/transfer-a-call-inline-ncco) to the survey NCCO. To do that, you must store the user and the agent leg identifiers:
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +> In the real-life case, you should implement a cache to store the pairs of user/agent leg identifiers and. The sample code shown in this tutorial will work properly only for one concurrent call.
"In A real-life SCENARIO" (or "situation" or "use case" but not just "case". Also this sentence is incomplete (ends with "and")

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +Extend your event webhook with REST API update call method with inline NCCO with `talk` and `input` actions to move the user leg to the survey part:
```suggestion
Extend your event webhook with a call to the `update` method, supplying an inline NCCO that contains `talk` and `input` actions to direct the user to the survey:
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +Add survey webhook to print the results:
```suggestion
Create the survey webhook to print the results:
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +3. Open the dial pad and press 1 or 2.
```suggestion
3. Using your phone's dial pad press either 1 or 2.
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +3. Answer the inbound call on your second mobile phone (you have to use at least two devices to get the scenario working; alternatively, you may use some calling application, for example, [Vonage Bus
If you need two devices, let's say this right at the beginning of the use case.

Let's also state here which device is the agent, etc so that we can stop referring to them as "first", "second", etc

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +With Vonage Voice API you can empower your existing contact center solution with IVR of any logic complexity, which depends only on your target use case and is virtually unlimited. Or you can build y
```suggestion
With the Vonage Voice API you can empower your existing contact center solution with sophisticated IVR logic that meets the needs of your business and customers. Or you can build your own solution from scratch using the Voice API and [Client SDK](/client-sdk/overview). Switching between the scripted part of the call and live conversation enables you to create a seamless customer experience.
```

2021-01-29 15:32 UTC, marklewin commented on _use_cases/en/contact-center.md
> +## Where Next?
Capitalize first letter of bullets please

2021-01-29 15:32 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +NCCO and webhooks allow scripting the call as a series of messages and questions to the user, which is applicable to [voice notifications](/use-cases/voice-alerts), [IVR](/use-cases/interactive-voice
```suggestion
NCCO and webhooks allow scripting the call as a series of messages and questions to the user, which is applicable to [voice notifications](/use-cases/voice-alerts), [IVR](/use-cases/interactive-voice-response), [voice assistants](/use-cases/asr-use-case-voice-bot) and other scenarios with a predefined list of possible events. With an NCCO, the application may instruct the Vonage platform to play the audio message ([text-to-speech](/voice/voice-api/guides/text-to-speech) or [prerecorded](/voice/voice-api/ncco-reference#stream)) and then expect user input either with [DTMF](/voice/voice-api/guides/dtmf) or [speech](/voice/voice-api/guides/asr). When the user has made a menu selection, your application is notified and is able to direct the call appropriately by supplying new call instructions in the form of an NCCO.
```

2021-01-29 15:32 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +In some scenarios, for example, a [Private Voice Communication](/use-cases/private-voice-communication) use case, it’s required to connect two or more participants to establish a live conversation. E
```suggestion
In some scenarios, for example, a [private voice communication](/use-cases/private-voice-communication) use case, you want to connect two or more participants to establish a live conversation. Each call, inbound or outbound, is automatically added to the new conversation behind the scenes. To connect it to another call with an NCCO, the application can either
```

2021-01-29 15:32 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +* create a new outbound call with the [`connect`](/voice/voice-api/ncco-reference#connect) action - it will be automatically joined to the same conversation;
Please capitalise first letter of all bullets

2021-01-29 15:32 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +Using a sequence of `connect` actions, the application may join other members in the conversation (up to 50 total conversation participants).
```suggestion
Using a sequence of `connect` actions, the application may add other members to the conversation (up to 50 total conversation participants).
```

2021-01-29 15:32 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +IVR usually has one or more options to speak to a live agent, sales, or support person. Also, in some cases a live conversation may end up with some scripted parts. For example, a customer satisfacti
```suggestion
IVR usually has one or more options to speak to a live agent, sales, or support person. Also, in some cases a live conversation may end up with some scripted parts. For example, a customer satisfaction survey. The Voice API allows switching from one form of interaction to another so that the call flow may consist of three (or more in  complex cases) parts:
```

2021-01-29 15:33 UTC, marklewin requested changes
Accidentally approved previous changes!

2021-01-29 16:34 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +Both inbound and outbound calls initially follow the same call flow once answered. This call flow is controlled by an NCCO. An NCCO is a script of actions to be run within the context of the call. Ac
It is a bit weird, but indeed both inbound and outbound are controlled with NCCO anyway. Despite the call is answered by the callee to get the connection established, the very next step is to get NCCO from the answer URL and follow the actions there (if it's not provided as `ncco` param in the initial request - which is almost the same anyway). So the only different thing with inbound is outbound is actually the direction of the connection: either the user is calling to Vonage to Vonage is calling to the user - the further process is exactly the same. Btw, if the NCCO returned from the answer URL is invalid (or answer URL is simply unreachable), the behaviour is quite user un-friendly: the phone rings, the user answers, and the call is immediately dropped.

Also, this sentence is not changed anyhow comparing to the [existing guide](https://developer.nexmo.com/voice/voice-api/guides/call-flow#overview).

2021-02-01 16:42 UTC, vshisterov commented on _use_cases/en/contact-center.md
> +  "from": <USER_NUMBER>,
I couldn't find a proper standard name for this... could you please advise?

2021-02-01 16:49 UTC, vshisterov commented on _use_cases/en/contact-center.md
> +3. Answer the inbound call on your second mobile phone (you have to use at least two devices to get the scenario working; alternatively, you may use some calling application, for example, [Vonage Bus
Added to **Prerequisites**

2021-02-01 16:53 UTC, vshisterov commented on _use_cases/en/contact-center.md
> +      departmentNumber = <YOUR_MOBILE_NUMBER>
Can I use something custom like {{AGENT_NUMBER}}? Or could you please advise which of the standard ones can be used here?

2021-02-02 07:47 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +You may choose to provide your NCCO as part of the request you send to create a call instead of providing an `answer_url`. This is done by providing an NCCO in the `ncco` key of your request.
```suggestion
You may choose to provide your NCCO as part of the request you send to create a call instead of providing an `answer_url`. This is done by providing a `ncco` attribute in the NCCO object of your request.
```

2021-02-02 07:48 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +when the Vonage API platform receives a call on your Vonage number, it makes an HTTP request to the `answer_url` provided. For inbound calls, the `answer_url` is configured in your [Voice Application
```suggestion
When the Vonage API platform receives a call on your Vonage number, it makes an HTTP request to the `answer_url` provided. For inbound calls, the `answer_url` is configured in your [Voice Application](/application/overview). For outbound calls, you provide an `answer_url` in the API request that creates the call.
```

2021-02-02 07:50 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/call-flow.md
> +During the call, Vonage is performing callback requests to the application at the `event_url`, set in the application configuration or in the NCCO action, if one is provided in the NCCO. There are tw
Yes, I think "making callback requests" is clearer, too. 

The distinction between "Voice Application", "application configuration",  and a "voice application (i.e. your own app with vapi capabilities) has always been quite confusing to explain.

2021-02-05 11:20 UTC, bencgreenberg approved these changes
Really great improvement, thanks @vshisterov for iterating on this together!

2021-02-05 11:20 UTC, bencgreenberg approved these changes

2021-02-05 11:20 UTC, merged