WhatsApp Provisioning API DEVX-4915
Nexmo/nexmo-developer pull request #3539
Opened 2021-02-03 15:21 UTC by niati

## Description

Review App

2021-02-03 15:56 UTC, slorello89 requested changes

2021-02-03 15:56 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/overview.md
> +The first thing you must do is [add a phone number](/add-phone-number) in your WhatsApp Business account dashboard.
the link here is broken think we're looking for `messages/whatsapp-provisioning/add-phone-number`

2021-02-03 15:56 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/overview.md
> +Once you've added a phone number, you may [provision your WhatsApp deployment](/provision-deployment).
This link isn't working - try `/messages/whatsapp-provisioning/provsion-deployment`

2021-02-03 15:56 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/overview.md
> +Finally, you may use the [Vonage API Dashboard](https://dashboard.nexmo.com/messages/social-channels) to [manage your WhatsApp Business profile](/manage-profile).
this link isn't working - think we need `/messages/whatsapp-provisioning/manage-profile`

2021-02-03 15:56 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/add-phone-number.md
> +You may now [provision your WhatsApp deployment](/provision-deployment).
Link isn't working

2021-02-03 15:56 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/manage-profile.md
> +1. Navigate to the [Social Channels page(https://dashboard.nexmo.com/messages/social-channels)] on the Vonage API dashboard.
improperly coupled square brackets are breaking this link.

2021-02-03 15:56 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/manage-profile.md
> +## Reference
I think we should call out here that we can also manage this programmatically - some of our partners may want to build their own dashboards for customers so they'll be interested in doing it programmatically - not sure we need to do much more than point people at the appropriate method in the API Reference.

2021-02-03 17:48 UTC, niati commented on _documentation/en/messages/whatsapp-provisioning/manage-profile.md
> +## Reference
There's a mention of it in the opening. Can't figure out how to link directly to that section. Do you think we need to add more about it?

2021-02-09 14:04 UTC, slorello89 commented on _documentation/en/messages/whatsapp-provisioning/manage-profile.md
> +## Reference
ok - I see what I missed, below you refer to the `External Accounts API Reference`, that's actually the WhatsApp provisioning API you're referring to, I'd call it such - external accounts is a separate API.

2021-02-11 14:47 UTC, niati commented on _documentation/en/messages/whatsapp-provisioning/manage-profile.md
> +## Reference
Good catch! Made the change. Let me know whenever this is ready to go out of Draft status and I'll change it so you can review/approve/merge.

2021-02-15 13:34 UTC, laurenannmarie commented
Should we add a note or tool tip around the OTP methods. E.g some numbers can't receive calls from the US so if you have one of those, use SMS. Or if you don't have the number on your device because its a virtual number you can divert to your own mobile device in the dashboard? (Or is this one of these things we do but shouldn't be doing as I appreciate it totally undermines the security aspect of the OTP...

2021-02-15 13:50 UTC, laurenannmarie commented
Typo in first line of Managing WhatsApp Profile - "Once cluster has been successfully deployed" -> Once *your*/*the*/*a*?

2021-02-15 14:49 UTC, laurenannmarie commented
The only 2 things I think might be missing are: 
1. Something along the lines of  "If you don't have a WhatsApp business account via Facebook and if you aren't already a customer of Vonage using WhatsApp please contact sales" (To stop users struggling through this using the WhatApp Business App or their personal WhatsApp numbers.)
2. The way this is linked to applications. There's one line about creating an application but it doesn't say why you should do this or how you link it (or perhaps I'm missing something)

2021-02-16 16:08 UTC, slorello89 commented
@niati - I agree with all of Lauren's comments - I think after they are incorporated this is ready to go.

2021-02-18 14:42 UTC, niati commented
> The only 2 things I think might be missing are:
> 
> 1. Something along the lines of  "If you don't have a WhatsApp business account via Facebook and if you aren't already a customer of Vonage using WhatsApp please contact sales" (To stop users struggling through this using the WhatApp Business App or their personal WhatsApp numbers.)
> 2. The way this is linked to applications. There's one line about creating an application but it doesn't say why you should do this or how you link it (or perhaps I'm missing something)

Updated addressing the following: 

1. Missing word "the cluster" - See [Manage WhatsApp Business profile](https://nexmo-developer-pr-3539.herokuapp.com/messages/whatsapp-provisioning/manage-profile) page
2. Note about contacting sales if the customer doesn't have a WhatsApp business account - See [Overview](https://nexmo-developer-pr-3539.herokuapp.com/messages/whatsapp-provisioning/overview) page
3. Note clarifying linking WhatsApp account to Vonage account via the dashboard - See [Provision a WhatsApp deployment](https://nexmo-developer-pr-3539.herokuapp.com/messages/whatsapp-provisioning/provsion-deployment) page.

2021-02-18 15:03 UTC, laurenannmarie commented
GREAT! Happy with this

2021-02-18 15:08 UTC, slorello89 approved these changes
LGTM 👍

2021-02-18 16:03 UTC, merged