DEVX-5226 Convert blog post to tutorial
Nexmo/nexmo-developer pull request #3555
Opened 2021-02-16 09:38 UTC by bencgreenberg

DEVX-5226 Convert Ruby blog post to tutorial

As specified in the Jira ticket, this converts the [Stream audio to a call](https://www.nexmo.com/legacy-blog/2019/01/24/play-streaming-audio-to-a-call-with-ruby-dr) blog post to a new ADP tutorial.

2021-02-19 08:14 UTC, bencgreenberg commented
@marklewin, Do you have some time to review this? 🙏🏻

2021-02-19 10:03 UTC, marklewin commented
> @marklewin, Do you have some time to review this? 🙏🏻

As it's you @bencgreenberg ... :)

2021-02-19 10:40 UTC, marklewin requested changes
This is great @bencgreenberg - I've just made a few suggestions. Going forward, I think it would be good to combine this tutorial with the .NET version to create a single, multi-language tutorial and keep our nav menu tidy. If you agree, please raise a ticket for me after this is merged and I'll deal with it 😄

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/create-voice-rubyproj.md
> +Inside the folder create a `server.rb` and `.env` files:
```suggestion
Inside the folder create two files: `server.rb` and `.env`:
```

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/create-voice-rubyproj.md
> +title: Create Server Folder and Files
Would be nice if the title of the step (on the RHS) matched the heading "Create the Project Folder and Files"

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/create-voice-rubyproj.md
> +title: Create Server Folder and Files
Interestingly, from this point onwards, in the deployment app, there are no Next/Previous buttons? 🤔

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/add-env-variables.md
> +Create a new file in the root folder of the project called `.env`. This file will contain environment variables for the Vonage API credentials we will need to use the Vonage Voice API.
You already created the `.env` file in Step 3.

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/require-dependencies.md
> +Near the top of the `server.rb` file add the following `require` statements to include the dependencies into the application:
"Include the dependencies _into_ the app" or "Include the dependencies _in_ the app"? I prefer the latter :)

2021-02-19 10:40 UTC, marklewin commented on config/tutorials/en/play-audio-ruby.yml
> +    1. Place a call with streamed audio played into it
```suggestion
    1. Place a call and stream audio into it
```
^^ A little bit clearer?

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/define-constants.md
> +The Vonage Voice API sends back call information to the webhook addresses we provided in the Vonage Voice Application in the API Dashboard. To receive that data we need an externally accessible URL.
```suggestion
The Vonage Voice API sends back call information to the webhook addresses we provided in the Vonage Voice Application in the API Dashboard. To receive that data we need an externally accessible URL. This tutorial uses ngrok to provide an externally available URL. For more information on setting up ngrok, follow [this tutorial](https://developer.nexmo.com/tools/ngrok).
```

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/define-constants.md
> +BASE_URL =
Would be nice to show a sample Ngrok URL here, to give the reader some idea of what ngrok URLs look like.

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/create-routes.md
> +We will add three HTTP routes to the `server.rb` file, two `GET` routes and one `POST` route:
Can we explain briefly what each route is responsible for?

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/run-app.md
> +In your terminal navigate to the directory of the application and execute the following command:
Can we say "project directory" here instead, to disambiguate the whole app/Application thing?

2021-02-19 10:40 UTC, marklewin commented on _tutorials/en/voice/voice-api/play-audio-ruby/run-app.md
> +This will start the application on `http://localhost:4567`. Making a web request to that URL will initiate a new call.
For new developers, it would be good to show (or at least suggest) how to do this. Postman, Curl, etc.

2021-02-22 09:31 UTC, bencgreenberg commented
@marklewin I believe this is ready for another review 🙏🏻

2021-02-22 12:55 UTC, marklewin approved these changes
Fabulous! Thanks @bencgreenberg

2021-02-22 12:56 UTC, merged