Create fraud-prevention.md
Nexmo/nexmo-developer pull request #3568
Opened 2021-02-22 18:25 UTC by vshisterov

## Description

Basic voice calling fraud prevention hints.

2021-02-23 11:19 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Like in every business, there are always persons and companies trying to get profit unfairly in the world of telephony communications. Vonage is performing a set of automatic and manual actions and p
I think we need a better descriptor for the negative practice you are describing. The modifier "unfair" is too vague. Is that an assault on capitalism in general or specific illegal practices?

2021-02-23 11:20 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Like in every business, there are always persons and companies trying to get profit unfairly in the world of telephony communications. Vonage is performing a set of automatic and manual actions and p
```suggestion
Like in every business, there are always persons and companies trying to get profit unfairly in the world of telephony communications. Vonage undertakes a series of automatic and manual actions and processes to protect you from fraud activities. Still, there are certain practices to follow which may help you avoid business impact and potential losses.
```

2021-02-23 11:21 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Typical fraud schemes are based on using for outbound calling specific phone numbers, also known as "premium destinations" or "revenue shared numbers", so that the fraudsters get money for each secon
I don't know what this sentence means. Can you please rephrase this part:

> Typical fraud schemes are **based on using for outbound calling specific phone numbers**, also known as "premium destinations" or "revenue shared numbers"

2021-02-23 11:22 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Typical fraud schemes are based on using for outbound calling specific phone numbers, also known as "premium destinations" or "revenue shared numbers", so that the fraudsters get money for each secon
I'm also not sure how to rephrase this sentence but it needs more clarity:

> To do that, they should either know your API key and secret or use your service UI/API, which allows entering the destination phone number, for example, login or reset password page using two-factor authentication with a voice call.

2021-02-23 11:23 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +If your business operates in certain countries, you may restrict the destination number to be in these countries. Alternatively, you may restrict certain destination, for example, blocking the follow
```suggestion
If your business operates in certain countries, you may restrict the destination number to those countries. Alternatively, you may restrict an entire destination, blocking the following country numbers, which are often used for fraud activities:
```

2021-02-23 11:24 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +* Congo
General question -- While statistically, this may be true, is it good practice to list these countries as recommended to block entirely? Perhaps some more data references should be added? Otherwise, it does come off as a bit discriminatory.

2021-02-23 11:25 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +In order to allow/block destinations, you may check the destination number (`from`) before performing Vonage API request for outbound call creation (`POST /calls` request or `connect` NCCO action) ei
```suggestion
In order to allow/block destinations, you may check the destination number (`from`) before performing a Vonage API request for an outbound call creation (`POST /calls` request or `connect` NCCO action) either by:
```

2021-02-23 11:29 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, use this construction:
```suggestion
Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, you can use this construction:
```

2021-02-23 11:58 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +* Congo
Competitors do it as well, e.g. https://www.twilio.com/docs/usage/anti-fraud-developer-guide#programmable-voice has the list

2021-02-23 13:20 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Like in every business, there are always persons and companies trying to get profit unfairly in the world of telephony communications. Vonage is performing a set of automatic and manual actions and p
Well, they definitely are not using the service as it supposed to be used like there is no real communication happening, just silence or fake tones or just random music - so there is no value in these calls in terms of information exchange between people and surely there is no usage of 2FA codes or messages delivered with the call. The only purpose is to get the money from the company(s). Though officially it's not really "illegal" from what I know, still I would say it doesn't fall under "fair usage" - which is a kind of widely used term.

2021-02-23 16:22 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +description: Learn basic voice calling fraud prevention practices
```suggestion
description: Protect your Voice API applications from fraud
```

2021-02-23 16:22 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Like in every business, there are always persons and companies trying to get profit unfairly in the world of telephony communications. Vonage is performing a set of automatic and manual actions and p
If these practices are not really "illegal", are we comfortable calling them "fraudulent"?

2021-02-23 16:43 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Like in every business, there are always persons and companies trying to get profit unfairly in the world of telephony communications. Vonage is performing a set of automatic and manual actions and p
I'm pretty sure we can: 
1) there is no other purpose of doing these calls rather than getting/sharing this premium destination fee: the fraudsters misusing our customer services, e.g. using two-factor authentication calls not to get the temporary password but just to make our customer pay them for the call
2) some of our customers suffer from it for tens and hundreds of thousands euros monthly 
3) our competitors explicitly call it "fraud" as well

2021-02-23 16:53 UTC, marklewin requested changes
Some stylistic changes for readability/clarity

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Typical fraud schemes are based on the generation of outbound calls to specific phone numbers known as "premium destinations" or "revenue shared numbers", so that the fraudsters get money for each se
Don't say that fraudsters "should" know your API key and secret. They will have gained access to it via fraudulent means.

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +If you have any suspicions that your dashboard credentials or API key/secret were compromised, update it as soon as possible. You can change your password in the Dashboard [Edit profile](https://dash
```suggestion
If you have any suspicions that your dashboard credentials or API key/secret have been compromised, update themas soon as possible. You can change your password in the Dashboard [Edit profile](https://dashboard.nexmo.com/edit-profile) page and request a new API secret on the [Settings](https://dashboard.nexmo.com/settings) page. See also [Best Security Practices for your Vonage Account](https://help.nexmo.com/hc/en-us/articles/115014939548).
```

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +If your business operates in certain countries, you may restrict the destination number to those countries. Alternatively, you may restrict an entire destination, blocking the following country numbe
```suggestion
If your business only operates in certain countries, you might choose to create an "allow list" to restrict calls to those countries. Alternatively, you can create a "block list" that allows calls to be made anywhere except to those countries in the list.

Some users elect to prevent calls from being placed to countries that are perceived as being high risk. These include:
```

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, you can use this construction in JavaScript:
Refer to allow list and block list rather than first approach/second approach

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +With its comparable simplicity, the drawback here is that, for the example above, `+1` phone country code corresponds not only to the US and Canada but a few other countries/regions which might be ou
```suggestion
The flaw with this approach is that the `+1` phone country code allows calls not only to the US and Canada but also the Bahamas, Antigua and Barbuda, which might not be your intention. You can target countries more precisely by using the Number Insight API:
```

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Other types of attacks might target getting access to your application or customer private data. In this type of attack, a fraudster impersonates Vonage and makes webhook requests to your application
```suggestion
Other types of attacks might attempt to gain access to your application or your customers' private data. In these attacks, a fraudster impersonates the Vonage Platform by making webhook requests to your application. These can reveal the voice message text which could contain sensitive data. To ensure that requests to your webhooks are from Vonage, you can:
```

2021-02-23 16:53 UTC, marklewin commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +* setup a firewall to accept requests from [Vonage IP ranges](https://help.nexmo.com/hc/en-us/articles/115004859247-Which-IP-addresses-should-I-whitelist-in-order-to-receive-voice-traffic-from-Nexmo-
Please capitalise first letter in bullet points

2021-02-23 17:08 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, you can use this construction in JavaScript:
I meant "check first digits of the number" by "the first approach" here... Anyway seems it needs better wording here, thinking of it now.

2021-02-23 17:09 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +With its comparable simplicity, the drawback here is that, for the example above, `+1` phone country code corresponds not only to the US and Canada but a few other countries/regions which might be ou
the Bahamas and Antigua and Barbuda are not the only countries with "+1", just an example (which btw also falls under "risk destination" according to what we see in our customer's experience). Can we keep "for example" somewhere here?

2021-02-23 17:32 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, you can use this construction in JavaScript:
@bencgreenberg could we make anyhow nice tabbed examples in different coding languages here?

2021-02-24 07:46 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +With its comparable simplicity, the drawback here is that, for the example above, `+1` phone country code corresponds not only to the US and Canada but a few other countries/regions which might be ou
I think we need to differentiate between a guide to fraud prevention vs a reference doc. I am reading this new file as the former, so it doesn't need to be comprehensive in listing every example in a single reference sentence. That would be better placed in a reference doc, which would read less like prose in any case.

2021-02-24 07:47 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, you can use this construction in JavaScript:
We could, but see my comment above. I don't think it's necessary for a guide that is functioning as a best practices doc, and not a tutorial or a reference documentation.

2021-02-24 09:58 UTC, vshisterov commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Assuming you want to allow calls to, for example, the United States and Canada only, with the first approach, you can use this construction in JavaScript:
Makes sense! 👍

2021-02-24 11:15 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +| These include (but not limited to):
```suggestion
| These include (but are not limited to):
```

2021-02-24 11:17 UTC, bencgreenberg commented on _documentation/en/voice/voice-api/guides/fraud-prevention.md
> +Like in other businesses, there are people and companies trying to profit unfairly in the world of telephony communications. Vonage undertakes a series of automatic and manual actions and processes t
Based on the earlier conversation on the distinction between fraudulent and illegal, can we rephrase this to not be "profit unfairly" as I think that doesn't capture the intention. Profit unfairly could mean they mark up prices too much and customers could save more elsewhere, not fraudulent practices.

2021-02-24 11:47 UTC, bencgreenberg approved these changes
Great job, @vshisterov! This will be a nice contribution to the docs.

2021-02-24 11:47 UTC, merged