Update CAPI events guide
Nexmo/nexmo-developer pull request #3645
Opened 2021-04-23 12:42 UTC by abdulajet

## Description

Please describe what the changes are made in this pull request and why the change was necessary.
Cross referenced events with those on the API spec to find missing events, then searched on kibana to see which events actually get used by the webhooks.

2021-04-23 13:49 UTC, pardel requested changes
Please see comment on Audio clasification.

2021-04-23 13:49 UTC, pardel commented on _documentation/en/conversation/concepts/event.md
> +`leg:status:update` |
I don't think leg:status:update` & `app:knocking:cancel` should be under audio...

2021-04-23 14:23 UTC, abdulajet commented on _documentation/en/conversation/concepts/event.md
> +`leg:status:update` |
@ash30 should they be in a general section maybe?

2021-05-17 11:30 UTC, ash30 commented on _documentation/en/conversation/concepts/event.md
> +`leg:status:update` |
Yeah I would agree, general section seems better fit.
A leg could be any media, not just audio.
And app:knocking is more a communication thing with backend, not just for audio.

2021-05-17 11:32 UTC, ash30 reviewed
apart from paul's already commented on, looks good.

2021-05-17 11:33 UTC, ash30 approved these changes

2021-05-17 15:46 UTC, pardel approved these changes
LGTM

2021-05-17 15:46 UTC, merged