Update/cli docs
Nexmo/nexmo-developer pull request #3806
Opened 2021-09-19 00:48 UTC by kellyjandrews

## Description

Vonage CLI is going GA - these updates look to modify the current state of the docs using all the new syntax.

## Deploy Notes

Just markdown changes

2021-09-20 18:11 UTC, superchilled requested changes

2021-09-20 18:11 UTC, superchilled commented on _documentation/en/number-insight/guides/number-insight-via-cli.md
As per standard, could mention that there will be a prompt:

```
This operation will charge your account. Proceed?
```

2021-09-20 18:11 UTC, superchilled commented on _documentation/en/number-insight/overview.md
Typo: vinage

2021-09-20 18:11 UTC, superchilled commented on _documentation/en/numbers/code-snippets/buy.md
`#buying-a-number` fragment identifier is unnecessary.

2021-09-20 18:17 UTC, superchilled commented on _documentation/en/numbers/code-snippets/cancel.md
#cancelling-a-number fragment identifier is unnecessary.

2021-09-21 03:43 UTC, kellyjandrews commented on _documentation/en/application/vonage-cli.md
> +
replace with: 
```
vonage apps:create "Test Application 1" --voice_event_url=http://example.com/webhooks/event --voice_answer_url=http://example.com/webhooks/answer --rtc_event_url=http://example.com/webhooks/rtcevent
```

2021-09-21 03:44 UTC, kellyjandrews commented on _documentation/en/application/vonage-cli.md
> +
It does.

2021-09-21 03:45 UTC, kellyjandrews commented on _documentation/en/number-insight/guides/number-insight-via-cli.md
Yes - sorry :(

2021-09-21 03:46 UTC, kellyjandrews commented on _documentation/en/number-insight/guides/number-insight-via-cli.md
>  ```
Yes - let's do that as well.

2021-09-21 03:46 UTC, kellyjandrews commented on _documentation/en/number-insight/guides/number-insight-via-cli.md
same

2021-09-21 03:47 UTC, kellyjandrews commented on _documentation/en/numbers/code-snippets/buy.md
I didn't make that discretion - just replacing what's there

2021-09-21 03:47 UTC, kellyjandrews commented on _documentation/en/numbers/code-snippets/cancel.md
see other comment

2021-09-21 03:47 UTC, kellyjandrews commented on _documentation/en/application/overview.md
Please double-check and correct this if needed.

2021-09-21 03:48 UTC, kellyjandrews commented on _documentation/en/application/vonage-cli.md
> +
Good point - would you be able to write that section?

2021-09-21 03:48 UTC, kellyjandrews commented on _documentation/en/application/vonage-cli.md
> +
yes - please update

2021-09-21 03:49 UTC, kellyjandrews commented on _documentation/en/client-sdk/overview.md
>  * [Tutorials](/client-sdk/tutorials)
Correct

2021-09-21 03:50 UTC, kellyjandrews commented on _documentation/en/client-sdk/setup/create-your-application.md
>  ```
I think I intended it at first - but now I hate it.

2021-09-21 03:52 UTC, kellyjandrews commented on _documentation/en/client-sdk/setup/create-your-application.md
>  ```
Users will soon be a core plugin and not need installation - it won't be tomorrow, but I didn't want to update the docs twice.

2021-09-21 03:53 UTC, kellyjandrews commented on _documentation/en/number-insight/guides/number-insight-via-cli.md
If you think it would help - add it in.

2021-09-21 10:57 UTC, superchilled approved these changes

2021-09-21 14:09 UTC, merged