Get user session guide
Nexmo/nexmo-developer pull request #3886
Opened 2021-11-24 15:38 UTC by abdulajet

Added a user session guide for JS and android

2021-11-24 16:29 UTC, pardel commented
Are the session calls based on user ID rather than username?! This is probably the first time it happens...

2021-11-24 17:59 UTC, conshus commented
> Are the session calls based on user ID rather than username?! This is probably the first time it happens...

Do you mean like the actual key name `user_id`? Yeah, I think this is the first time. Previously, for like getUser, you just pass in an `id` like getUser(id), no object or anything. 

I don't think I've seen any `username` keys. There's `name` and `display_name` when creating a user on the server.

2021-11-24 18:00 UTC, conshus commented on _documentation/en/client-sdk/in-app-messaging/guides/get-user-sessions.md
> +This guide covers how to get the a user's active [sessions](/conversation/concepts/session), which can be used as a way to show an online status.
```suggestion
This guide covers how to get a user's active [sessions](/conversation/concepts/session), which can be used as a way to show their online status. 
```

2021-11-24 18:01 UTC, conshus commented on _documentation/en/client-sdk/in-app-messaging/guides/get-user-sessions.md
> +Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and you are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation)
```suggestion
Before you begin, make sure you [added the SDK to your app](/client-sdk/setup/add-sdk-to-your-app) and are able to [create a conversation](/client-sdk/in-app-messaging/guides/simple-conversation).
```

2021-11-24 18:14 UTC, conshus requested changes
Looks really good. Just a couple of things I noted.
Also, I see that there are `Note` in some of the guides about the tutorial for the chat application that the chat app doesn't cover. Do we want to add them to the chat app or remove the note?

2021-11-25 14:50 UTC, abdulajet commented
> Also, I see that there are `Note` in some of the guides about the tutorial for the chat application that the chat app doesn't cover. Do we want to add them to the chat app or remove the note?

I am not sure what you mean by this, like the chat app doesn't have the feature in the guide?

2021-11-29 15:57 UTC, conshus commented
> > Also, I see that there are `Note` in some of the guides about the tutorial for the chat application that the chat app doesn't cover. Do we want to add them to the chat app or remove the note?
> 
> I am not sure what you mean by this, like the chat app doesn't have the feature in the guide?

Yeah, exactly. We are linking them to a tutorial that doesn't showcase the feature we are talking about on the page.

2021-11-30 14:42 UTC, conshus approved these changes
Everything looks good to me.

2021-12-02 14:36 UTC, merged