APIDOC-114: Update Sign-in button destination URL
Nexmo/nexmo-developer pull request #3903
Opened 2021-12-08 02:57 UTC by VinayB09

Update the Sign in button destination URL to https://identity.nexmo.com/login

2021-12-14 13:21 UTC, pardel requested changes

2021-12-14 13:21 UTC, pardel commented on config/business_info.yml
> +      path: https://identity.nexmo.com/login
@niati @VinayB09 Do we want to remove the tracking information here?

2021-12-14 14:10 UTC, niati commented on config/business_info.yml
> +      path: https://identity.nexmo.com/login
@pardel you mean from dashboard.nexmo.com? If so, BI told us to add the tracking to the new URL.

2021-12-14 14:15 UTC, niati commented on config/business_info.yml
> +      path: https://identity.nexmo.com/login
I see what you're saying - it appears that we didn't add it to the identity URL.

2021-12-16 19:04 UTC, VinayB09 commented on config/business_info.yml
> +      path: https://identity.nexmo.com/login
Added icid to the. new URL.

2021-12-17 13:04 UTC, marcoranieri approved these changes

2021-12-17 15:33 UTC, merged