Apidoc 111
Nexmo/nexmo-developer pull request #3906
Opened 2021-12-08 15:11 UTC by NickCW99

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2021-12-08 15:34 UTC, NickCW99 commented
Created Meetings API documentation as described in this outline: https://github.com/avital-vonage/meetings-api-docs/blob/master/docs.md
Ticket: https://jira.vonage.com/browse/APIDOC-111
Waiting for Meetings API Ref links to be setup

2021-12-08 15:48 UTC, niati commented on _documentation/en/meetings/overview.md
> +* [Requirements](#requirements). What you will need to get started.
Some of the cross-ref links here are not working. Also, remove the periods (.) after the x-ref links.

2021-12-08 16:02 UTC, niati commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +* **API Key and Secret** Once you’re logged in, you'll find your API Key and Secret in your dashboard under "Getting Started".
Can we include a hyperlink to the Dashboard menu to which we're referring? Is this it? https://dashboard.nexmo.com/getting-started/meetings-api

References to items on the UI do not go in quotes - i.e. "Getting Started" - you should apply bold font to any UI label. In this case, however, I would just reword "Once you're logged in to the Dashboard, you'll find your API Key and Secret on the Meetings API menu." Hyperlink to the Meetings API menu text to the actual dashboard page.

Also, when I land on the "Try the Meetings API" page, I have to Request Access to get started. Should that be included as a step here? That is probably a question for @avital-vonage

2021-12-08 16:10 UTC, niati commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +* **Vonage Developer Account** If you don’t have a Vonage account yet, you can get one  here: [Vonage Developers Account](https://dashboard.nexmo.com/sign-up).
Include a colon after each bullet point item in bold font - i.e. **Vonage Developer Account:**

2021-12-08 16:13 UTC, niati commented on _documentation/en/meetings/overview.md
> +  * is created for a meeting happening now.
Remove 'is' from these bullet points.
Make sure the first word in each bullet point is capitalized.

2021-12-08 16:38 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +* **API Key and Secret** Once you’re logged in, you'll find your API Key and Secret in your dashboard under "Getting Started".
Yes, I agree, probably similar in long term room. I'll change them both.

2021-12-08 16:41 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +* **Vonage Developer Account** If you don’t have a Vonage account yet, you can get one  here: [Vonage Developers Account](https://dashboard.nexmo.com/sign-up).
Done

2021-12-08 16:46 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +  * is created for a meeting happening now.
Done. Also line 33 create long term room long term should be long_term

2021-12-08 17:04 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +
Done

2021-12-08 17:05 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +* [Requirements](#requirements). What you will need to get started.
Done, will push them through with your other changes

2021-12-08 17:07 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +  * is created for a meeting happening now.
Line 65, missing an end period.

2021-12-12 13:29 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +* [Room Types](#room-types): Defines the types of rooms available
end of sentence periods are not consistent. My preference is without, considering these aren't full sentences.

2021-12-12 13:30 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +## Setup POST Request
Set up is two words

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +How to setup an Instant (default) room using the Meetings API.
set up should be two rooms

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +
saying "is enabled" is inaccurate. It's an encoded string you need to create with your api key +secret, and i think we should be explicit about that. no need to send the developer searching for the answer

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +You need to provide the following:
You "need" to provide the following is misleading when some params are required and some aren't. We should remove this sentence entirely or reword the sentence.

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +**POST Endpoint**: The (POST) endpoint when creating a meeting room is: ``https://api.vonage.com/beta/meetings/rooms``.
This was my mistake. That won't work. Let's use `https://api-eu.vonage.com/beta/meetings/rooms`

Also, can we reword to "The endpoint for creating a meeting room is:"

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/room-management.md
> +Notice the ``ID`` received in the response. This is the ``ID`` of the room which will be used for room retrieval:
...using a GET request.

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/room-management.md
> +* **Participant Joined** ``participant-joined``: A notification about someone joining a session.
dash in participant-joint. should be a colon. my mistake, sorry

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/room-management.md
> +> A notification that a session has started.
Not sure it's accurate to put these in > format. I would just change these descriptions to regular text (for the following ones as well)

2021-12-12 13:44 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/room-management.md
> +Recordings are associated with the session in which they occurred. To retrieve or manage recordings, you'll need the recording ID, which can be found in the callbacks.
backticks on ID :)

2021-12-13 09:04 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/room-management.md
> +Notice the ``ID`` received in the response. This is the ``ID`` of the room which will be used for room retrieval:
Done

2021-12-13 09:04 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/room-management.md
> +* **Participant Joined** ``participant-joined``: A notification about someone joining a session.
Changed * **Participant Joined** to ``*participant:joint**``....

Is this correct, should it be **participant:joined**?

2021-12-13 09:13 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +* [Room Types](#room-types): Defines the types of rooms available
Yes, these, we use periods when there is a leading sentence with colon. Done

2021-12-13 09:15 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +## Setup POST Request
Yes, setup is a noun, set up is US verb, set-up is UK English verb. Changed to set up, both instance (line 9 as well).

2021-12-13 09:16 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +How to setup an Instant (default) room using the Meetings API.
Changed to set up.

2021-12-13 09:26 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +
I've checked to see what done elsewhere in the docs. Changed to 

`**Authorization**: Log into your [Vonage API Dashboard](https://dashboard.nexmo.com) to create your `VONAGE_API_KEY` and `VONAGE_API_SECRET`. You use the API key and secret for basic [Authentication](/concepts/guides/authentication).`

2021-12-13 10:07 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +You need to provide the following:
I agree, only the display name is required. 

I've converted the list to a table, similar for long term meeting room. This means we can add extra fields and values. Comments very welcome. I nearly did this is a table in the first place:

![image](https://user-images.githubusercontent.com/85564614/145792537-77515bdd-a2a4-471d-a9f1-fab5f20b344d.png)

2021-12-13 10:19 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +**POST Endpoint**: The (POST) endpoint when creating a meeting room is: ``https://api.vonage.com/beta/meetings/rooms``.
Done

2021-12-13 11:38 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +
No, you are not creating the api key and secret. 

**Authorization**: Log into your [Vonage API Dashboard](https://dashboard.nexmo.com) to retrieve your VONAGE_API_KEY and VONAGE_API_SECRET. You'll combine these to create a [basic Authentication](/concepts/guides/authentication) string.

2021-12-13 11:39 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +You need to provide the following:
Much better. love it.

2021-12-13 11:40 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/room-management.md
> +* **Participant Joined** ``participant-joined``: A notification about someone joining a session.
yes. 
notice that it's joined and not joint :)

2021-12-13 11:56 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/room-management.md
> +Recordings are associated with the session in which they occurred. To retrieve or manage recordings, you'll need the recording ID, which can be found in the callbacks.
Done

2021-12-13 12:11 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +* **API Key and Secret** Once you’re logged in, you'll find your API Key and Secret in your dashboard under "Getting Started".
Sorry, just seeing this now. 

* **Meetings API Activation** To activate the Meetings API, you'll need to register your account. Please send an email request containing your API Key to the [Meetings API Team](mailto:meetings-api@vonage.com). 
You can also try it out in the [Vonage Dashboard](https://dashboard.nexmo.com/getting-started/meetings-api).

2021-12-13 12:26 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/room-management.md
> +> A notification that a session has started.
There's a few of these, I'd like to find out what @niati (Nick Iati) thinks. Then we can target and define what a  note actually is.

2021-12-13 12:27 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/room-management.md
> +* **Participant Joined** ``participant-joined``: A notification about someone joining a session.
OK, just wondered.

2021-12-13 12:51 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +How to setup an Instant (default) room using the Meetings API.
done, set up and set-up are US/UK verbs setup is a noun, as you correctly pointed out it is the wrong word, thanks.

2021-12-13 14:27 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +
Done. I see what you mean, sorry,

2021-12-14 16:03 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +  * **Session**: the time in which there are participants present in the room. Defined as from the first participant to join, until the last to leave.
...."Defined as all events that occur during this time, from when the first participant joins, until the last to leave."

2021-12-14 16:05 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +  * **Record**: you can record a meeting either manually during the meeting or automatically when sending a request.
**Record**: you can record a meeting manually during the meeting, or automatically when a session is started.

2021-12-14 16:05 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +  * **Callbacks**: allow you to receiver information about a session.
**Callbacks**: allow you to receive information about a session.

(Typo on receiver)

2021-12-14 16:27 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +  * **Callbacks**: allow you to receiver information about a session.
Missed one, well caught!

2021-12-16 16:45 UTC, NickCW99 commented
1. Please can a curl dev check the changes we have made to standardise the curl code snippets. These are in

- Create an Instant Room
- Create a Long Term Room
- Meeting Room Management
- Callbacks

2. I've also added the api ref URL at the end of overview.md and the meetings api link in the left nav bar is working now.
3. Extra line in the code snippets list removed from overview.md#reference (at the end of the page)

2021-12-16 16:53 UTC, NickCW99 commented
Please can a curl dev check the changes we have made to standardise the curl code snippets. These are in

- Create an Instant Room
- Create a Long Term Room
- Meeting Room Management

I've also added the api ref URL at the end of overview.md and the meetings api link in the left nav bar is working now.
Extra line in the code snippets list removed from overview.md#reference (at the end of the page)

2021-12-23 22:52 UTC, NickCW99 commented
The Cross ref for the following link was incorrect. Not only did I not test it correctly, it was not caught by automated testing and reviews. One for the future :-) 

![image](https://user-images.githubusercontent.com/85564614/147297600-46ded73f-5bc3-4a76-aec5-6a69505e2af6.png)

2022-01-10 16:15 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +* **API Key and Secret**: Once you’re logged in to the [Vonage API Dashboard](https://dashboard.nexmo.com), you'll find your API Key and Secret on the Meetings API menu.
Slight change to meet in-house standards.

2022-01-10 16:21 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-instant-room.md
> +**Authorization**: Log into your [Vonage API Dashboard](https://dashboard.nexmo.com) to retrieve your `VONAGE_API_KEY` and `VONAGE_API_SECRET`. You'll combine these to create a [Basic Authentication]
Slight changes to meet in-house standards.

2022-01-10 16:42 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/create-long-term-room.md
> +-H 'Authorization: basic YWFhMDEyOmFiYzEyMzQ1Njc4OQ==' \
FYI: Also added the two pieces of **Authorization** and **Application ID and Secret** content, so it is the same as instant room

2022-01-12 08:29 UTC, avital-vonage requested changes

2022-01-12 08:29 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +**Meetings API Activation**: To activate the Meetings API, you need to register with us. Please send an email request to the [Meetings API Team](mailto:meetings-api@vonage.com).
with your API Key from the [Vonage API Dashboard](https://dashboard.nexmo.com).

2022-01-12 08:29 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +**API Key and Secret**: Once you’re logged in, you'll find your API Key and Secret in your dashboard under "Getting Started".
**Application ID and Private Key**: Once you’re logged in to the [Vonage API Dashboard](https://dashboard.nexmo.com), click on Applications and create a new Application. Click  `Generate public and private key` and record the private key. 

**JSON Web Token (JWT)**: Use [this generator](https://developer.vonage.com/jwt) to create a JWT using the Application ID and Private Token mentioned above. For further details about JWTs, please see [Vonage Authentication](/concepts/guides/authentication).

2022-01-12 08:29 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +Key | Description
i think we should remove this section as it's no longer relevant. what do you think?

2022-01-12 08:55 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +**Meetings API Activation**: To activate the Meetings API, you need to register with us. Please send an email request to the [Meetings API Team](mailto:meetings-api@vonage.com).
Done

2022-01-12 08:56 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +**API Key and Secret**: Once you’re logged in, you'll find your API Key and Secret in your dashboard under "Getting Started".
Done with slight changes

2022-01-12 08:56 UTC, NickCW99 commented on _documentation/en/meetings/overview.md
> +Key | Description
Removed

2022-01-12 14:07 UTC, avital-vonage approved these changes

2022-01-12 14:07 UTC, avital-vonage commented on _documentation/en/meetings/overview.md
> +**Application ID and Private Key**: Once you’re logged in to the [Vonage API Dashboard](https://dashboard.nexmo.com), click on Applications and create a new Application. Click Generate ``public and p
**Application ID and Private Key**: Once you’re logged in to the [Vonage API Dashboard](https://dashboard.nexmo.com), click on Applications and create a new Application. Generate a public and private key and record the private key.

2022-01-12 15:39 UTC, avital-vonage commented on _documentation/en/meetings/code-snippets/room-management.md
> +> The expiration date of a long term room can be updated by using a PATCH action and the room ID. The new date should be included in an object called ``update_details``.
Please replace line 45 with whats in line 46. We changed things entirely.

2022-01-12 16:14 UTC, NickCW99 commented on _documentation/en/meetings/code-snippets/room-management.md
> +> The expiration date of a long term room can be updated by using a PATCH action and the room ID. The new date should be included in an object called ``update_details``.
So delete line 45

2022-01-12 17:49 UTC, niati approved these changes

2022-01-12 17:49 UTC, merged