Update node.md
Nexmo/nexmo-developer pull request #4439
Opened 2022-08-04 16:06 UTC by conshus

Removes standalone instead include full SDK and some options not yet available in beta version

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

2022-08-04 18:29 UTC, dragonmantank requested changes
LGTM

2022-08-22 14:59 UTC, dragonmantank approved these changes
LGTM

2022-08-22 17:04 UTC, dragonmantank requested changes
Changing some instances of `Id` back to `ID`

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +the total number of archives your App Id has generated.
I think a search/replace got a big aggressive.

In normal text, I think we should keep it fully capitalized as "ID", but in code examples we just camelCase it to "Id"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +call the `OpenTok.startBroadcast()` method. Pass in three parameters: the session Id for the
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +broadcast Id (the `id` property of the Broadcast object) as the first parameter. The second
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +Call the `Opentok.getBroadcast()` method, passing in a broadcast Id, to get a Broadcast object.
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +the total number of broadcasts your App Id has generated.
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +passing in the broadcast Id and the [layout
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +feature. This requires a SIP URI, the session Id you wish to add the audio-only stream to, and a
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +token to connect to that session Id.
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +      " added to session Id: " +
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +passing in a session Id and a callback function. Upon success, the callback function is invoked
Should revert this to keep "ID"

2022-08-22 17:04 UTC, dragonmantank commented on _documentation/en/video/server-sdks/node.md
> +You need a Vonage App Id and private key, which you can obtain by logging into your
Should revert this to keep "ID"

2022-09-26 10:19 UTC, pardel commented
@conshus could you implement the change request above so we can merge this ticket?

2022-12-01 11:42 UTC, pardel commented
@EDDYMENS could you give this another look?

2022-12-13 16:57 UTC, merged