updated python sdk changelog
Nexmo/nexmo-developer pull request #4750
Opened 2022-12-01 03:19 UTC by maxkahan

Updating changelog

2022-12-01 10:35 UTC, pardel requested changes

2022-12-01 10:35 UTC, pardel commented on _changelogs/server_sdk/vonage-python-sdk.md
> +## 3.2.0b0
Can we label this 4.0.0b0? The Video integration project might drag and we'll need to add new products in Q1 so might create issues with versioning.
Also, please make sure to update the ADP changelog?

2022-12-08 03:54 UTC, maxkahan commented
@pardel I've made your requested changes.

2022-12-08 13:01 UTC, SMadani approved these changes

2022-12-08 13:17 UTC, merged